#pragma once
#ifndef NETWORK_MODULE_NETWORK_DEFINE_H
#define NETWORK_MODULE_NETWORK_DEFINE_H

enum HEADER_SIZE_TYPE
{
    HEADER_SIZE_BODY,       // BODY 부분만
    HEADER_SIZE_TOTAL,      // BODY + HEADER 포함
};

#endif //NETWORK_MODULE_NETWORK_DEFINE_H