

FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT1_GENERATOR(  0), byTempArray, 0,	GETRNDNO_RNG128_T2(194));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT1_GENERATOR(  7), byTempArray, 1,	GETRNDNO_RNG128_T2( 31));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT1_GENERATOR(  1), byTempArray, 2,	GETRNDNO_RNG128_T2( 39));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT1_GENERATOR(  6), byTempArray, 3,	GETRNDNO_RNG128_T2(238));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT1_GENERATOR(  4), byTempArray, 4,	GETRNDNO_RNG128_T2(150));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT1_GENERATOR(  3), byTempArray, 5,	GETRNDNO_RNG128_T2(  8));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT1_GENERATOR(  5), byTempArray, 6,	GETRNDNO_RNG128_T2( 13));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT1_GENERATOR(  2), byTempArray, 7,	GETRNDNO_RNG128_T2(106));


