

FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_DWORD1_GENERATOR(  0), byTempArray, 0,	GETRNDNO_RNG128_T2(203));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_DWORD1_GENERATOR(  2), byTempArray, 1,	GETRNDNO_RNG128_T2(197));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_DWORD1_GENERATOR(  3), byTempArray, 2,	GETRNDNO_RNG128_T2( 15));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_DWORD1_GENERATOR(  1), byTempArray, 3,	GETRNDNO_RNG128_T2(106));


