

FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT2_GENERATOR(  3), byTempArray, 0,	GETRNDNO_RNG128_T4(135));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT2_GENERATOR(  1), byTempArray, 1,	GETRNDNO_RNG128_T4(117));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT2_GENERATOR(  6), byTempArray, 2,	GETRNDNO_RNG128_T4(242));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT2_GENERATOR(  2), byTempArray, 3,	GETRNDNO_RNG128_T4(114));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT2_GENERATOR(  7), byTempArray, 4,	GETRNDNO_RNG128_T4( 79));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT2_GENERATOR(  0), byTempArray, 5,	GETRNDNO_RNG128_T4( 58));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT2_GENERATOR(  5), byTempArray, 6,	GETRNDNO_RNG128_T4(235));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT2_GENERATOR(  4), byTempArray, 7,	GETRNDNO_RNG128_T4(123));

