

FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT2_GENERATOR(  0), byTempArray, 0,	GETRNDNO_RNG128_T5( 81));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT2_GENERATOR(  3), byTempArray, 1,	GETRNDNO_RNG128_T5( 93));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT2_GENERATOR(  2), byTempArray, 2,	GETRNDNO_RNG128_T5( 57));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT2_GENERATOR(  5), byTempArray, 3,	GETRNDNO_RNG128_T5(210));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT2_GENERATOR(  4), byTempArray, 4,	GETRNDNO_RNG128_T5(151));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT2_GENERATOR(  7), byTempArray, 5,	GETRNDNO_RNG128_T5( 10));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT2_GENERATOR(  1), byTempArray, 6,	GETRNDNO_RNG128_T5(255));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT2_GENERATOR(  6), byTempArray, 7,	GETRNDNO_RNG128_T5( 67));

