

FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_DWORD2_GENERATOR(  2), byTempArray, 0,	GETRNDNO_RNG128_T5(195));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_DWORD2_GENERATOR(  0), byTempArray, 1,	GETRNDNO_RNG128_T5( 68));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_DWORD2_GENERATOR(  3), byTempArray, 2,	GETRNDNO_RNG128_T5(124));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_DWORD2_GENERATOR(  1), byTempArray, 3,	GETRNDNO_RNG128_T5( 41));

