

FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_DWORD1_GENERATOR(  0), byTempArray, 0,	GETRNDNO_RNG128_T3(165));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_DWORD1_GENERATOR(  1), byTempArray, 1,	GETRNDNO_RNG128_T3(103));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_DWORD1_GENERATOR(  2), byTempArray, 2,	GETRNDNO_RNG128_T3(199));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_DWORD1_GENERATOR(  3), byTempArray, 3,	GETRNDNO_RNG128_T3( 87));


