

FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT1_GENERATOR(  4), byTempArray, 0,	GETRNDNO_RNG128_T3(128));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT1_GENERATOR(  0), byTempArray, 1,	GETRNDNO_RNG128_T3( 17));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT1_GENERATOR(  2), byTempArray, 2,	GETRNDNO_RNG128_T3(109));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT1_GENERATOR(  7), byTempArray, 3,	GETRNDNO_RNG128_T3( 51));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT1_GENERATOR(  6), byTempArray, 4,	GETRNDNO_RNG128_T3(  5));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT1_GENERATOR(  3), byTempArray, 5,	GETRNDNO_RNG128_T3( 77));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT1_GENERATOR(  1), byTempArray, 6,	GETRNDNO_RNG128_T3(182));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT1_GENERATOR(  5), byTempArray, 7,	GETRNDNO_RNG128_T3( 30));


