

FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_DWORD1_GENERATOR(  0), byTempArray, 0,	GETRNDNO_RNG128_T1(185));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_DWORD1_GENERATOR(  3), byTempArray, 1,	GETRNDNO_RNG128_T1( 52));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_DWORD1_GENERATOR(  2), byTempArray, 2,	GETRNDNO_RNG128_T1(225));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_DWORD1_GENERATOR(  1), byTempArray, 3,	GETRNDNO_RNG128_T1(145));

