

FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT1_GENERATOR(  3), byTempArray, 0,	GETRNDNO_RNG128_T1(211));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT1_GENERATOR(  1), byTempArray, 1,	GETRNDNO_RNG128_T1( 45));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT1_GENERATOR(  6), byTempArray, 2,	GETRNDNO_RNG128_T1(144));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT1_GENERATOR(  2), byTempArray, 3,	GETRNDNO_RNG128_T1(174));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT1_GENERATOR(  7), byTempArray, 4,	GETRNDNO_RNG128_T1(239));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT1_GENERATOR(  0), byTempArray, 5,	GETRNDNO_RNG128_T1(129));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT1_GENERATOR(  5), byTempArray, 6,	GETRNDNO_RNG128_T1( 38));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_OCT1_GENERATOR(  4), byTempArray, 7,	GETRNDNO_RNG128_T1(158));

