

FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_DWORD2_GENERATOR(  1), byTempArray, 0,	GETRNDNO_RNG128_T4(153));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_DWORD2_GENERATOR(  0), byTempArray, 1,	GETRNDNO_RNG128_T4(218));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_DWORD2_GENERATOR(  2), byTempArray, 2,	GETRNDNO_RNG128_T4(213));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_DWORD2_GENERATOR(  3), byTempArray, 3,	GETRNDNO_RNG128_T4( 22));

