

FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX2_GENERATOR(  0), byTempArray, 0,	GETRNDNO_RNG128_T4( 80));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX2_GENERATOR(  7), byTempArray, 1,	GETRNDNO_RNG128_T4(188));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX2_GENERATOR(  5), byTempArray, 2,	GETRNDNO_RNG128_T4( 11));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX2_GENERATOR( 11), byTempArray, 3,	GETRNDNO_RNG128_T4(219));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX2_GENERATOR( 12), byTempArray, 4,	GETRNDNO_RNG128_T4(236));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX2_GENERATOR(  3), byTempArray, 5,	GETRNDNO_RNG128_T4(126));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX2_GENERATOR(  4), byTempArray, 6,	GETRNDNO_RNG128_T4(212));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX2_GENERATOR(  2), byTempArray, 7,	GETRNDNO_RNG128_T4( 83));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX2_GENERATOR( 14), byTempArray, 8,	GETRNDNO_RNG128_T4( 95));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX2_GENERATOR(  9), byTempArray, 9,	GETRNDNO_RNG128_T4( 44));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX2_GENERATOR( 15), byTempArray, 10,	GETRNDNO_RNG128_T4(140));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX2_GENERATOR(  6), byTempArray, 11,	GETRNDNO_RNG128_T4(127));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX2_GENERATOR(  8), byTempArray, 12,	GETRNDNO_RNG128_T4( 23));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX2_GENERATOR( 10), byTempArray, 13,	GETRNDNO_RNG128_T4(103));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX2_GENERATOR( 13), byTempArray, 14,	GETRNDNO_RNG128_T4( 69));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX2_GENERATOR(  1), byTempArray, 15,	GETRNDNO_RNG128_T4( 66));

