

FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR( 10), byTempArray, 0,	GETRNDNO_RNG128_T1(211));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  4), byTempArray, 1,	GETRNDNO_RNG128_T1( 45));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  1), byTempArray, 2,	GETRNDNO_RNG128_T1(144));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  7), byTempArray, 3,	GETRNDNO_RNG128_T1(174));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR( 12), byTempArray, 4,	GETRNDNO_RNG128_T1(239));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  0), byTempArray, 5,	GETRNDNO_RNG128_T1(129));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  5), byTempArray, 6,	GETRNDNO_RNG128_T1( 38));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR( 11), byTempArray, 7,	GETRNDNO_RNG128_T1(158));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  8), byTempArray, 8,	GETRNDNO_RNG128_T1(194));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  6), byTempArray, 9,	GETRNDNO_RNG128_T1( 31));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR( 15), byTempArray, 10,	GETRNDNO_RNG128_T1( 39));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  9), byTempArray, 11,	GETRNDNO_RNG128_T1(238));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  3), byTempArray, 12,	GETRNDNO_RNG128_T1(150));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR( 14), byTempArray, 13,	GETRNDNO_RNG128_T1(  8));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  2), byTempArray, 14,	GETRNDNO_RNG128_T1( 13));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR( 13), byTempArray, 15,	GETRNDNO_RNG128_T1(106));


