

FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  4), byTempArray, 0,	GETRNDNO_RNG128_T3( 81));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR( 14), byTempArray, 1,	GETRNDNO_RNG128_T3( 93));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR( 15), byTempArray, 2,	GETRNDNO_RNG128_T3( 57));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR( 11), byTempArray, 3,	GETRNDNO_RNG128_T3(210));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR( 13), byTempArray, 4,	GETRNDNO_RNG128_T3(151));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  0), byTempArray, 5,	GETRNDNO_RNG128_T3( 10));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  7), byTempArray, 6,	GETRNDNO_RNG128_T3(255));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  8), byTempArray, 7,	GETRNDNO_RNG128_T3( 67));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  1), byTempArray, 8,	GETRNDNO_RNG128_T3(225));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  6), byTempArray, 9,	GETRNDNO_RNG128_T3( 18));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR( 12), byTempArray, 10,	GETRNDNO_RNG128_T3( 91));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  5), byTempArray, 11,	GETRNDNO_RNG128_T3(104));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR( 10), byTempArray, 12,	GETRNDNO_RNG128_T3(221));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  3), byTempArray, 13,	GETRNDNO_RNG128_T3(  4));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  9), byTempArray, 14,	GETRNDNO_RNG128_T3( 61));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  2), byTempArray, 15,	GETRNDNO_RNG128_T3(199));

