

FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  3), byTempArray, 0,	GETRNDNO_RNG128_T2(128));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  8), byTempArray, 1,	GETRNDNO_RNG128_T2( 17));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  5), byTempArray, 2,	GETRNDNO_RNG128_T2(109));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR( 13), byTempArray, 3,	GETRNDNO_RNG128_T2( 51));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  2), byTempArray, 4,	GETRNDNO_RNG128_T2(  5));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  7), byTempArray, 5,	GETRNDNO_RNG128_T2( 77));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  0), byTempArray, 6,	GETRNDNO_RNG128_T2(182));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR( 10), byTempArray, 7,	GETRNDNO_RNG128_T2( 30));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  4), byTempArray, 8,	GETRNDNO_RNG128_T2(135));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  9), byTempArray, 9,	GETRNDNO_RNG128_T2(117));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR( 12), byTempArray, 10,	GETRNDNO_RNG128_T2(242));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR( 11), byTempArray, 11,	GETRNDNO_RNG128_T2(114));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR( 15), byTempArray, 12,	GETRNDNO_RNG128_T2( 79));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  1), byTempArray, 13,	GETRNDNO_RNG128_T2( 58));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR(  6), byTempArray, 14,	GETRNDNO_RNG128_T2(235));
FI_ENCODE_LIST_NODE(pbySrcArray, FI_KEY_HEX1_GENERATOR( 14), byTempArray, 15,	GETRNDNO_RNG128_T2(123));


