#ifndef __ACHIEVEMENT_ACHIEVEMENTDEFINE_H
#define __ACHIEVEMENT_ACHIEVEMENTDEFINE_H
#pragma once


//업적 과제 코드
enum ACHIEVEMENT_OBJECT_TYPE
{
    ACHIEVEMENT_OBJECT_NOT_DEFINE = 0,
    ACHIEVEMENT_OBJECT_ITEM,            //아이템 획득
    ACHIEVEMENT_OBJECT_NPC,             //NPC 사냥 (NPC 코드로 구분) 
    ACHIEVEMENT_OBJECT_NPC_AC,          //NPC 사냥 (AC 코드로 구분)
    ACHIEVEMENT_OBJECT_MISSION,         //미션 달성
    ACHIEVEMENT_OBJECT_ACCOMPLISHMENT,  //달성률 달성
	ACHIEVEMENT_OBJECT_CURSETOWER,      //저주의탑 완료
	ACHIEVEMENT_OBJECT_QUEST,           //퀘스트
    ACHIEVEMENT_OBJECT_COLLECT,         //채집
	ACHIEVEMENT_OBJECT_ITEM_GET,		//아이템 습득 횟수
	ACHIEVEMENT_OBJECT_ITEM_EQUIP,		//아이템 장착
	ACHIEVEMENT_OBJECT_PC_KILL,			// PC Kill
	ACHIEVEMENT_OBJECT_PC_KILL_ACCUMULATED, //누적 PC Kill
	ACHIEVEMENT_OBJECT_NPC_KILL,			// NPC Kill
	ACHIEVEMENT_OBJECT_NPC_KILL_ACCUMULATED,//누적 NPC Kill
	ACHIEVEMENT_OBJECT_KILL,				// PC,NPC Kill
	ACHIEVEMENT_OBJECT_KILL_ACCUMULATED,	//누적 PC,NPC Kill
	ACHIEVEMENT_OBJECT_WIN,					// 우승횟수
	ACHIEVEMENT_OBJECT_FALL,				// 추락사
	ACHIEVEMENT_OBJECT_MISSION_CLEAR_TIME,	// 미션 클리어 시간
	ACHIEVEMENT_OBJECT_LEVELUP,				// 레벨달성
	ACHIEVEMENT_OBJECT_BATTLE_HEAL,				// 힐링
	ACHIEVEMENT_OBJECT_BATTLE_DAMAGE_TOP,		// 최고 데미지
	ACHIEVEMENT_OBJECT_BATTLE_DAMAGE_TO_MONSTER,// 가해 데미지
    ACHIEVEMENT_OBJECT_BATTLE_DAMAGE_BY_MONSTER,// 피해 데미지
    ACHIEVEMENT_OBJECT_BATTLE_KILL,             // 킬수
	ACHIEVEMENT_OBJECT_BATTLE_DEAD,				// 사망횟수
	ACHIEVEMENT_OBJECT_AC_CLEARE,               // AC완료
    ACHIEVEMENT_OBJECT_SKILL_STEP,              // 스킬 단계 해제
    ACHIEVEMENT_OBJECT_PERK_LEVEL,              // 퍽 레벨 달성
    ACHIEVEMENT_OBJECT_ITEM_SCORE,              // 장비 평가 점수 달성
    ACHIEVEMENT_OBJECT_FAME,                    // 명성 달성
    ACHIEVEMENT_OBJECT_REPUTE,                  // 평판 달성
    ACHIEVEMENT_OBJECT_FAME_COUNT,              // 명성 달성 개수
    ACHIEVEMENT_OBJECT_REPUTE_COUNT,            // 평판 달성 개수
    ACHIEVEMENT_OBJECT_COMPLETE_NORMALQUEST,    // 일반 퀘스트 완료
    ACHIEVEMENT_OBJECT_COMPLETE_DAILYQUEST,     // 일일 퀘스트 완료
    ACHIEVEMENT_OBJECT_COMPLETE_DAILYQUEST_CONTINOUS, // 일일 퀘스트 연속 완료
    ACHIEVEMENT_OBJECT_LOTTO,                   // 복권 당첨
    ACHIEVEMENT_OBJECT_KILL_ALL,                // 몬스터/캐릭터 제거 횟수
    ACHIEVEMENT_OBJECT_DEAD_ALL,                // (몬스터/캐릭터에 의해) 사망 횟수
    ACHIEVEMENT_OBJECT_ENCHANT, // 인첸트 등급 달성

#ifdef _NA_006593_20130327_ADD_ACHIEVEMENT_BATTLEGROUND
    ACHIEVEMENT_OBJECT_BATTLEGROUND_WIN,                    //전장 승리
    ACHIEVEMENT_OBJECT_BATTLEGROUND_STRONGPOINT_ATTACK,     // 전장 거점 공격
    ACHIEVEMENT_OBJECT_BATTLEGROUND_STRONGPOINT_DEFENSE,    // 전장 거점 방어    
#endif
    ACHIEVEMENT_OBJECT_MAX,
};

//보상 종류
enum ACHIEVEMNET_REWARD_TYPE
{
    ACHIEVEMENT_REWARD_NONE = 0,        //보상 없음
    ACHIEVEMENT_REWARD_CODE,            //rewardinfo.txt 의 코드로 보상
    ACHIEVEMENT_REWARD_ACCOMPLISHMENT,  //달성률 보상
};

//반환 타입
enum ACHIEVEMENT_RETURN
{
    AChiEVEMENT_ERROR = 1,


};

//
enum ACHIEVEMENT_SERIALIZE
{
	ACHIEVEMENT_SAVE,
	ACSERIALIZE_CLIENT_LOAD,
	ACSERIALIZE_DBPROXY_LOAD,
};

#endif //__ACHIEVEMENT_ACHIEVEMENTDEFINE_H
