#if defined(WAVERIX_USING_PCH_LIST)
#if defined(WAVERIX_PCH_BUILD_SELECT)

#define PRE_COMPILED_HEADER_INCLUDED

//==================================================================================================
// Utility
#include <time.h>
#include <set>
#include <list>
#include <fstream>
#include <io.h>
#include <time.h>
#include <vector>
#include <hash_map>
#include <hash_set>
#include <map>
#include <float.h>
#include <functional>

//==================================================================================================
#include <boost/tuple/tuple.hpp>
#include <boost/pool/pool.hpp>
#include <boost/pool/object_pool.hpp>
#include <boost/bind.hpp>
#include <boost/lambda/bind.hpp>
#include <boost/multi_index_container.hpp>
#include <boost/multi_index/member.hpp>
#include <boost/multi_index/ordered_index.hpp>

//==================================================================================================

#include <Define.h>
#include <UtilityCommon.h>

//==================================================================================================
// Utility

#include <UtilityCommon.h>
#include <CommonDef.h>

#include <SunSTL.Utiltiy.h>
#include <SunSTL.UtiltiyTMP.Def.h>
#include <SunSTL.UtiltiyTMP.h>

#include <WxRingBuffer.h>
#include <StreamHashKey.h>

#include <ArchiveOfStream.h>
#include <BaseParser.h>
#include <BitsetOperation.h>
#include <chunk_stl.h>
#include <CircuitQueue.h>
#include <CommonStruct.h>
#include <CriticalSection.h>
#include <ErrorControl.h>
//#include <Event.h>
#include <ExtractPacketData.h>
#include <FilePackerManager.h>
#include <Firewall.h>
#include <functional_custom.h>
#include <FunctionMap.h>
#include <GeneralFunction.h>
#include <GroupCounter.h>
#include <ICallBackInterface.h>
#include <INIParser.h>
#include <IThreadInterface.h>
#include <ITimeout.h>
#include <Linkedlist.h>
#include <LinkedListCS.h>
#include <List.h>
//#include <list_map.h>
//#include <ManualResetEvent.h>
#include <MemoryPoolFactory.h>
#include <MemoryPoolFactoryV.h>
#include <MultiIndexDataTable.h>
#include <ObjKeyGenerator.h>
#include <PerfCheck.h>
#include <Randomizer.h>
#include <RandomNumberGenerator.h>
#include <RatioSelector.h>
#include <ReliableRatioRandomizer.h>
#include <RingArray.h>
#include <RingBuffer.h>
#include <RingBufferEx.h>
#include <SafeMemoryPoolFactory.h>
#include <SafeStringBufferControl.h>
#include <safe_string.h>
#include <SharedMemoryPool.h>
#include <Singleton.h>
#include <SolarAssert.h>
#include <SolarDateTime.h>
#include <SolarDump.h>
#include <SolarFileReader.h>
#include <SolarHashTable.h>
#include <SolarSimpleConsole.h>
#include <Stackwalker.h>
#include <StatusCaretaker.h>
#include <TextFilter.h>
#include <ThreadPool.h>
#include <TimeConverter.h>


//==================================================================================================
// ProgramCommon

#include <PacketStruct.h>
#include <PacketStruct_CG.h>
#include <PacketStruct_CL.h>
#include <PacketStruct_CW.h>
#include <Protocol.h>
#include <Protocol_CG.h>
#include <Protocol_CL.h>
#include <Protocol_CW.h>
#include <Protocol_IGC.h>
#include <StructInPacket.h>
#include <PacketControl\CategoryLinkPair.h>
#include <PacketControl\PacketControl.h>
#include <PacketControl\PacketControl_AuthFlow.h>
#include <PacketControl\WarMessages.h>
#include <PacketControl\WarMessages_Sync.h>
#include <Battle.h>
#include <Const.h>
#include <CountryCode.h>
#include <Define.Build.h>
#include <Define.h>
#include <DefineForLog.h>
#include <Foreign.Build.h>
#include <Global.h>
#include <misc.h>
#include <PublicMath.h>
#include <ResultCode.h>
#include <SinTable.h>
#include <Struct.h>
#include <Struct_BasePlayerInfo.h>
#include <TriggerHeader.h>
#include <VarPacket.h>
#include <Version.h>
#include <CoolTimerFactory.h>
#include <SCCharacter.h>
#include <SCItem.h>
#include <SCNonCharacter.h>
#include <SCNPC.h>
#include <SCObject.h>
#include <SCPlayer.h>
#include <Attribute.h>
#include <CommonCharacterFormula.h>
#include <ItemAttrCalculator.h>
#include <ItemFormula.h>
#include <NPCAttributes.h>
#include <NumericValues.h>
#include <PlayerAttributes.h>
#include <SkillAttrCalculator.h>
#include <SCStream.h>
#include <SerializeStream.h>
#include <VersionControl.h>
#include <AccumulatePointParser.h>
#include <CharInfoParser.h>
#include <CollectionParser.h>
#include <DominationInfoParser.h>
#include <EnchantParser.h>
#include <EtherBulletInfoParser.h>
#include <ExchangeRewardInfo.h>
#include <ExpValueInfoParser.h>
#include <ExtraStoneOptionInfoParser.h>
#include <FateItemInfoParser.h>
#include <GameOptionParser.h>
#include <GroupInfoParser.h>
#include <GuildRankInfoParser.h>
#include <GuildRightInfoParser.h>
#include <HeroCustomInfoParser.h>
#include <InstantEnchantParser.h>
#include <ItemComposeListParser.h>
#include <ItemCompositeParser.h>
#include <ItemCrystalizeListParser.h>
#include <ItemInfoParser.h>
#include <ItemTypeList.h>
#include <LimitedItemInfoParser.h>
#include <LimitedOptionParser.h>
#include <LinearHash.h>
#include <LotteryInfoParser.h>
#include <Macro.h>
#include <MapInfoParser.h>
#include <MaxGuildMemberInfoParser.h>
#include <MissionRewardParser.h>
#include <NewCharItemInfoParser.h>
#include <NPCInfoParser.h>
#include <PetInfoParser.h>
#include <PKScriptParser.h>
#include <ProhibitionWordParser.h>
#include <RankOptionParser.h>
#include <RequireFieldLevelInfoParser.h>
#include <RewardInfoList.h>
#include <RidingInfoParser.h>
#include <ScriptCode.IParser.h>
#include <SetItemOptionInfoParser.h>
#include <ShopInfoParser.h>
#include <SkillInfoParser.h>
#include <SkillInventoryStoreParser.h>
#include <SocketOptionDescParser.h>
#include <SocketOptionParser.h>
#include <StateInfoParser.h>
#include <StrengthPenaltyParser.h>
#include <StrengthUIParser.h>
#include <StyleQuickRegistInfoParser.h>
#include <SunEventInfoParser.h>
#include <TableData.h>
#include <TestParser.h>
#include <TriggerParser.h>
#include <ScriptParserManager.h>
//#include <Base64.h>
//#include <md5.h>
//#include <PacketCrypt.h>
//#include <Seedx.h>
//#include <sha1.h>
//#include <Tea.h>
//#include <WZ_MD5.h>
//#include <AkCommon.h>
//#include <AKError.h>
//#include <AKHackReport.h>
//#include <AKLib.h>
//#include <AKLib_dll.h>
//#include <AKLibConfig.h>
//#include <armorkit.h>
//#include <ArmorKitDll.h>
//#include <CArmorKit.h>
//#include <IGhost.h>
//#include <IGhostUtil.h>
//#include <signature.h>
//#include <typedef_AKv1HackDetect.h>
//#include <CryptManager_4Client.h>
//#include <GameResourceInterface.h>
//#include <RandomSNKey_4Client.h>
#include <MissionManager.h>
#include <AreaTileLoadHelper.h>
#include <SlotInsertResultConvert.h>
#include <SSQ\SSQInfoParser.h>
#include <SSQ\SSQInfoStruct.h>
#include <SSQ\SSQPacketProc.h>
#include <SunAuth\AuthCountryCode.h>
#include <SunAuth\AuthDefine.Build.h>
#include <SunAuth\AuthDefine.h>
#include <SunAuth\AuthProtocol.h>
#include <SunAuth\AuthProtocol_CF.h>
#include <SunAuth\AuthStruct.h>
//#include <HanAuth\HanAuthForClient.h>
//#include <HanAuth\HanAuthForSvr.h>
//#include <hanauth\HanReportForClient.h>
//#include <hanauth\HanRTA.h>
//#include <hanauth\IOutBound.h>
//#include <stdafx.h>
//---#include <SkillSystem\PerkInfoParser.h>
//---#include <SkillSystem\PerkDataContainer.h>
#include <CubeSystem\CubeStruct.h>
#include <CubeSystem\CubeSystemParser.h>


//==================================================================================================
// AreaConqeust
#include <AreaConquest.h>
#include <AreaConquestHeader.h>
#include <AreaConquestInfo.h>
#include <AreaConquestInfoParser.h>
#include <AreaConquestStruct.h>

//==================================================================================================
// SolarSlot
#include <ISlotUpdater.h>
#include <ItemOptionHeader.h>
#include <SCFateInfo.h>
#include <SCItemFuncBranch.h>
#include <SCItemSlot.h>
#include <SCItemSlotContainer.h>
#include <SCItemStreamSerializer.h>
#include <SCLimitedInfo.h>
#include <SCLottoInfo.h>
#include <SCLuckyEliteInfo.h>
#include <SCNOption.h>
#include <SCPetInfo.h>
#include <SCQuickSlot.h>
#include <SCQuickSlotContainer.h>
#include <SCQuickStyleSlot.h>
#include <SCQuickStyleSlotContainer.h>
#include <SCRankInfo.h>
#include <SCRiderInfo.h>
#include <SCSkillSlot.h>
#include <SCSkillSlotContainer.h>
#include <SCSlot.h>
#include <SCSlotContainer.h>
#include <SCSlotFactory.h>
#include <SCSlotHeader.h>
#include <SCSlotStruct.h>
#include <SCSlotStruct_Version.h>
#include <SCSocketInfo.h>
#include <SCWayPointInfo.h>

//==================================================================================================
// PartyLib
#include <PartyDefine.h>
#include <PartyState.h>
#include <PartyStruct.h>
#include <BaseParty.h>
#include <BasePartyManager.h>
#include <Guidance.h>
#include <GuidanceManager.h>
#include <SessionMemberMgr.h>

//==================================================================================================
// Common

#include <PacketStruct_AD.h>
#include <PacketStruct_AG.h>
#include <PacketStruct_AM.h>
#include <PacketStruct_AU.h>
#include <PacketStruct_AW.h>
#include <PacketStruct_AZ.h>
#include <PacketStruct_DG.h>
#include <PacketStruct_DM.h>
#include <PacketStruct_DP.h>
#include <PacketStruct_DW.h>
#include <PacketStruct_DZ.h>
#include <PacketStruct_GM.h>
#include <PacketStruct_GP.h>
#include <PacketStruct_GS.h>
#include <PacketStruct_GZ.h>
#include <PacketStruct_MO.h>
#include <PacketStruct_MP.h>
#include <PacketStruct_MW.h>
#include <PacketStruct_MX.h>
#include <PacketStruct_MZ.h>
#include <PacketStruct_ServerCommon.h>
#include <PacketStruct_SM.h>
#include <PacketStruct_SX.h>
#include <PacketStruct_WZ.h>
#include <Protocol_AD.h>
#include <Protocol_AG.h>
#include <Protocol_AM.h>
#include <Protocol_AU.h>
#include <Protocol_AW.h>
#include <Protocol_AZ.h>
#include <Protocol_DG.h>
#include <Protocol_DM.h>
#include <Protocol_DP.h>
#include <Protocol_DW.h>
#include <Protocol_DZ.h>
#include <Protocol_GM.h>
#include <Protocol_GP.h>
#include <Protocol_GS.h>
#include <Protocol_GZ.h>
#include <Protocol_MO.h>
#include <Protocol_MP.h>
#include <Protocol_MW.h>
#include <Protocol_MX.h>
#include <Protocol_MZ.h>
#include <Protocol_ServerCommon.h>
#include <Protocol_SM.h>
#include <Protocol_SX.h>
#include <Protocol_WZ.h>
#include <ServerStructInPacket.h>
#include <ServerStruct.h>
#include <ServerCommonDef.h>
#include <ServerConst.h>
#include <ServerGlobal.h>
#include <SUNConsole.h>
#include <AbusingOptionParser.h>
#include <AIParamParser.h>
#include <ArmorDamageParser.h>
#include <CHuntingRewardParser.h>
#include <CurseTowerTimeParser.h>
#include <FatigueOptionParser.h>
#include <FileParser.h>
#include <FormulaRatioParser.h>
#include <GMCmdParser.h>
#include <GroupParser.h>
#include <MapPartialLoadingParser.h>
#include <MatchInfoParser.h>
#include <MonsterSummonParser.h>
#include <PointRankingParser.h>
#include <RegenParser.h>
#include <ScriptDataManager.h>
#include <ServerOptionParser.h>
#include <ServerOptionParserEx.h>
#include <SecureLog.h>
#include <SunLog.h>
#include <SunLog.Interfaces.h>
#include <ServerFrame.h>
#include <ServerSession.h>
#include <ServiceApp.h>
#include <TempServerSession.h>
#include <DropCore.h>
#include <DropRatioInfoList.h>
#include <ItemTypeDropRatio.h>
#include <StatisticsManager.h>
#include <CollectedList.h>
#include <ItemOwnFlag.h>
#include <ObjectKeyStream.h>
#include <ReadyState.h>
#include <WayPoint.h>
#include <WorkLoad\WorkLoad.Common.h>
#include <WorkLoad\WorkLoadContainer.h>
#include <WorkLoad\WorkLoadManager.h>
#include <WorkLoad\WorkLoadPacketStream.h>
//#include <AkSupport.h>
#include <SolarAuth.Common.h>
#include <SolarAuth.CryptFlowPolicy.h>
#include <SolarAuth.Interfaces.h>
#include <SSQ\SSQHandlerBase.h>
#include <SSQ\SSQPacketProcS2S.h>
#include <PacketControl\PacketControlS2S.h>
#include <SunAuth\AuthProtocol_GA.h>
#include <FriendInvitation\FriendInvitationCommand.h>
#include <FriendInvitation\FriendInvitationController.h>
#include <FriendInvitation\FriendInvitationInvoker.h>
#include <ServerBuildVersion.h>

//==================================================================================================

#include ".\BattleServer.h"
#include ".\FieldServer.h"
#include ".\GameServerEx.h"
#include ".\GameServerStruct.h"
#include ".\GeneralGameServerFunction.h"
#include ".\main.h"
#include ".\Status\ChangeAttrStatus.h"
#include ".\Status\EnchantPoisonStatus.h"
#include ".\Status\IntensifySummon.h"
#include ".\Status\SuctionStatus.h"
#include ".\Status\SummonStatus.h"
#include ".\Status\TransparentStatus.h"
#include ".\Status\VitalSuctionStatus.h"
#include ".\AgentServerSession.h"
#include ".\GameDBProxySession.h"
#include ".\GuildServerSession.h"
#include ".\MasterServerSession.h"
#include ".\PortalServerSession.h"
#include ".\RemoteServerSession.h"
#include ".\ShopServerSession.h"
#include ".\Character.h"
#include ".\Collection.h"
#include ".\CrystalWarp.h"
#include ".\FriendMonster.h"
#include ".\IGridObject.h"
#include ".\Item.h"
#include ".\LuckyMonster.h"
#include ".\MapNpc.h"
#include ".\MapObject.h"
#include ".\Merchant.h"
#include ".\Money.h"
#include ".\Monster.h"
#include ".\NonCharacter.h"
#include ".\NPC.h"
#include ".\Object.h"
#include ".\ObjectDefine.h"
#include ".\ObjectPolicy.h"
#include ".\Player.h"
#include ".\Player_Grid_Operator.h"
#include ".\SSQMonster.h"
#include ".\Summoned.h"
#include ".\SyncMerchant.h"
#include ".\TotemNpc.h"
#include ".\AppliedNpcDependencyChain.h"
#include ".\CPetManager.h"
#include ".\ExtraNPCManager.h"
#include ".\ObjectFactory.h"
#include ".\ObjectList.h"
#include ".\PlayerManager.h"
#include ".\PlayerRider.h"
#include ".\PostManager.h"
#include ".\SummonedNPCs.h"
#include ".\SummonManager.h"
#include ".\SystemMemo.h"
#include ".\CollectionManager.h"
#include ".\CollectionStateInfo.h"
#include ".\Npcai\AIMessageQueue.h"
#include ".\Npcai\AITypes.h"
#include ".\npcai\NPCStateFactory.h"
#include ".\npcai\NPCStateManager.h"
#include ".\Npcai\State.h"
#include ".\npcai\TargetFinder.h"
#include ".\TargetManager.h"
#include ".\Npcai\AttackState.h"
#include ".\BlindState.h"
#include ".\npcai\ChaosState.h"
#include ".\Npcai\DeadState.h"
#include ".\Npcai\DestroyObjectState.h"
#include ".\Npcai\FallApartState.h"
#include ".\Npcai\FlyingState.h"
#include ".\Npcai\FollowState.h"
#include ".\Npcai\HelpState.h"
#include ".\Npcai\IdleState.h"
#include ".\npcai\JumpState.h"
#include ".\Npcai\KnockDownState.h"
#include ".\Npcai\NoTransState.h"
#include ".\Npcai\PathListState.h"
#include ".\npcai\PatrolState.h"
#include ".\Npcai\RetreatState.h"
#include ".\Npcai\ReturnState.h"
#include ".\npcai\RunAwayState.h"
#include ".\npcai\SpawnIdleState.h"
#include ".\Npcai\SpecialDeadActionState.h"
#include ".\npcai\StopIdleState.h"
#include ".\Npcai\ThrustState.h"
#include ".\npcai\TrackAreaState.h"
#include ".\Npcai\TrackState.h"
#include ".\Npcai\WanderState.h"
#include ".\npcai\SummonIdle.h"
#include ".\ChangeMonsterAbility.h"
#include ".\EtherEmissionDevice.h"
#include ".\MovementChecker.h"
#include ".\MoveStateControl.h"
#include ".\PacketHandler\PacketHandler.h"
#include ".\PacketHandler\Handler_DG_CHARINFO.h"
#include ".\PacketHandler\Handler_DG_CONNECTION.h"
#include ".\PacketHandler\Handler_CG_AREACONQUEST.h"
#include ".\PacketHandler\Handler_CG_BATTLE.h"
#include ".\PacketHandler\Handler_CG_CHAO.h"
#include ".\PacketHandler\Handler_CG_CHARINFO.h"
#include ".\PacketHandler\Handler_CG_CHUNTING.h"
#include ".\PacketHandler\Handler_CG_COLLECT.h"
#include ".\PacketHandler\Handler_CG_CONNECTION.h"
#include ".\PacketHandler\Handler_CG_CONVERSATION.h"
#include ".\PacketHandler\Handler_CG_EVENT.h"
#include ".\PacketHandler\Handler_CG_GM.h"
#include ".\PacketHandler\Handler_CG_GUILD.h"
#include ".\PacketHandler\Handler_CG_ITEM.h"
#include ".\PacketHandler\Handler_CG_MAP.h"
#include ".\PacketHandler\Handler_CG_PARTY.h"
#include ".\PacketHandler\Handler_CG_PVP.h"
#include ".\PacketHandler\Handler_CG_QUEST.h"
#include ".\PacketHandler\Handler_CG_ROOM.h"
#include ".\PacketHandler\Handler_CG_SKILL.h"
#include ".\PacketHandler\Handler_CG_STATUS.h"
#include ".\PacketHandler\Handler_CG_STYLE.h"
#include ".\PacketHandler\Handler_CG_SUMMON.h"
#include ".\PacketHandler\Handler_CG_SYNC.h"
#include ".\PacketHandler\Handler_CG_TRADE.h"
#include ".\PacketHandler\Handler_CG_TRIGGER.h"
#include ".\PacketHandler\Handler_CG_VENDOR.h"
#include ".\PacketHandler\Handler_CG_WAREHOUSE.h"
#include ".\PacketHandler\Handler_CG_WAYPOINT.h"
#include ".\PacketHandler\Handler_Client.h"
#include ".\PacketHandler\Handler_GM.h"
#include ".\PacketHandler\Handler_AG_CHAO.h"
#include ".\PacketHandler\Handler_AG_CHARINFO.h"
#include ".\PacketHandler\Handler_AG_CHUNTING.h"
#include ".\PacketHandler\Handler_AG_CONNECTION.h"
#include ".\PacketHandler\Handler_AG_EVENT.h"
#include ".\PacketHandler\Handler_AG_GM.h"
#include ".\PacketHandler\Handler_AG_ITEM.h"
#include ".\PacketHandler\Handler_AG_PARTY.h"
#include ".\PacketHandler\Handler_AG_STATUS.h"
#include ".\PacketHandler\Handler_AG_ZONE.h"
#include ".\PacketHandler\Handler_GZ_GUILD.h"
#include ".\PacketHandler\Handler_PortalServer.h"
#include ".\PacketHandler\Handler_ShopServer.h"
#include ".\AppliedItemDependencyChain.h"
#include ".\FunctionalRestrictManager.h"
#include ".\ItemManager.h"
#include ".\ItemManager_Types.h"
#include ".\ItemManager_Util.h"
#include ".\QuickManager.h"
#include ".\QuickStyleManager.h"
#include ".\RatioManager.h"
#include ".\RewardManager.h"
#include ".\SlotManager.h"
#include ".\WareInvenProtector.h"
#include ".\TradeManager.h"
#include ".\TradeSlot.h"
#include ".\TradeSlotContainer.h"
#include ".\EquipmentSlotContainer.h"
#include ".\GameSCSlotFactory.h"
#include ".\GuildWareHouseSlotContainer.h"
#include ".\InventorySlotContainer.h"
#include ".\QuickSlotContainer.h"
#include ".\SkillSlotContainer.h"
#include ".\TempStoreSlotContainer.h"
#include ".\WarehouseSlotContainer.h"
#include ".\DropManager.h"
#include ".\VendorManager.h"
#include ".\VendorPage.h"
#include ".\VendorPageManager.h"
#include ".\VendorSlot.h"
#include ".\VendorSlotContainer.h"
#include ".\EventInventorySlotContainer.h"
#include ".\EventItemSlot.h"
#include ".\GameShop.BitBlockContainer.h"
#include ".\GameShop.IndexGenerator.h"
#include ".\GameShop.ShopItemBuilder.h"
#include ".\GameShopManager.h"
#include ".\GameShopUser.h"
#include ".\AccumulatePointImplement.h"
#include ".\BaseImplement.h"
#include ".\ComposeOrDecomposeImplement.h"
#include ".\CrystallizeImplement.h"
#include ".\CubeSystem\CubeSystemImplement.h"
#include ".\Slot\EtherealizeImpl.h"
#include ".\ImplementUtil.h"
#include ".\RandomItemImplement.h"
#include ".\RankUpImplement.h"
#include ".\SocketSystem\SocketSystemImplement.h"
#include ".\GameCHuntingRoom.h"
#include ".\GameDominationField.h"
#include ".\GameHuntingField.h"
#include ".\GameHuntingRoom.h"
#include ".\GameInstanceDungeon.h"
#include ".\GameLobbyRoom.h"
#include ".\GameMissionRoom.h"
#include ".\GamePVPRoom.h"
#include ".\GameRoom.h"
#include ".\GameVillage.h"
#include ".\World\GameWarControlManager.h"
#include ".\World\GameWarDistributionChart.h"
#include ".\GameZone.h"
#include ".\GameZoneCommon.h"
#include ".\GameZoneManager.h"
#include ".\World\HighLoadBalancer.h"
#include ".\ZoneReloader.h"
#include ".\Field.h"
#include ".\GameField.h"
#include ".\Sector.h"
#include ".\FieldInfo.h"
#include ".\MovingPlanner.h"
#include ".\SectorGrid.h"
#include ".\SectorInfo.h"
#include ".\SharedFieldInfo.h"
#include ".\Map.h"
#include ".\MapAllocator.h"
#include ".\MapDefine.h"
#include ".\MapInfo.h"
#include ".\MapInfoLoader.h"
#include ".\VarMsg.h"
#include ".\PVPCommon.h"
#include ".\PVPFormula.h"
#include ".\PVPInfo.h"
#include ".\PVPManager.h"
#include ".\CHuntingManager.h"
#include ".\CompetitionFormula.h"
#include ".\CompetitionInfo.h"
#include ".\CompetitionTeam.h"
#include ".\ResrcManager.h"
#include ".\ScriptRegenLoader.h"
#include ".\WUTLoader.h"
#include ".\UnitGroupManager.h"
#include ".\UnitListOfGroup.h"
#include ".\UnitGroupInfo.h"
#include ".\UnitGroupInfoManager.h"
#include ".\UnitRegen.h"
#include ".\UnitRegenManager.h"
#include ".\UnitRegenInfo.h"
#include ".\UnitRegenInfoManager.h"
#include ".\World\SSQ\SSQHandlerInGame.h"
#include ".\View.h"
#include ".\BattleRecorder.h"
#include ".\CHuntingBattleResult.h"
#include ".\DominationBattleResult.h"
#include ".\GameBattleResult.h"
#include ".\InstanceDungeonBattleResult.h"
#include ".\MissionBattleResult.h"
#include ".\PVPBattleResult.h"
#include ".\MissionPointManager.h"
#include ".\MissionRecordManager.h"
#include ".\MissionRewardManager.h"
#include ".\RankingSystemCtl.h"
#include ".\Trigger.h"
#include ".\TriggerAreaHash.h"
#include ".\TriggerLastedState.h"
#include ".\TriggerManagerEx.h"
#include ".\ActionTriggers.h"
#include ".\IActionTriggerEx.h"
#include ".\ConditionTriggers.h"
#include ".\IConditionTriggerEx.h"
#include ".\GameRankingManager.h"
#include ".\TutorialMission.h"
#include ".\Status\AnimationDelayControl.h"
#include ".\ApplySplashDamage.h"
#include ".\Ability.h"
#include ".\AbilityFactory.h"
#include ".\BaseStatusAbility.h"
#include ".\CancelStatusAbility.h"
#include ".\DamageAbility.h"
#include ".\ExhaustAbility.h"
#include ".\FightingEnergyAbility.h"
#include ".\InformationAbility.h"
#include ".\MonsterTransAbility.h"
#include ".\ResurrectionAbility.h"
#include ".\SelfDestructionAbility.h"
#include ".\StatusDamageAbility.h"
#include ".\SummonDeadMonsterAbility.h"
#include ".\TeleportAbility.h"
#include ".\AbnormalAbility.h"
#include ".\AbsorbAbility.h"
#include ".\AggroAbility.h"
#include ".\BlockSkillAbility.h"
#include ".\BonusDamageAbility.h"
#include ".\BuffStatusAbility.h"
#include ".\ChangeAttrAbility.h"
#include ".\CureAbility.h"
#include ".\DragonTransAbility.h"
#include ".\LowHPAbility.h"
#include ".\MagicShieldAbility.h"
#include ".\MirrorAbility.h"
#include ".\PeriodicDamageAbility.h"
#include ".\StunAbility.h"
#include ".\SuctionAbility.h"
#include ".\SummonToDeathAbility.h"
#include ".\ThrustAbility.h"
#include ".\TransparentAbility.h"
#include ".\VitalSuctionAbility.h"
#include ".\WindShieldAbility.h"
#include ".\BombEffectAbility.h"
#include ".\PeriodicEffectAbility.h"
#include ".\SummonAbility.h"
#include ".\SummonCrystalWarpAbility.h"
#include ".\PassiveStatusAbility.h"
#include ".\SPDamageAbility.h"
#include ".\WeaponMasteryAbility.h"
#include ".\BaseEffect.h"
#include ".\BombEffect.h"
#include ".\EffectFactory.h"
#include ".\EffectManager.h"
#include ".\PeriodicDamageEffect.h"
#include ".\Status\BaseStatus.h"
#include ".\Status\Status_Operator.h"
#include ".\Status\StatusFactory.h"
#include ".\Status\StatusManager.h"
#include ".\Status\AbilityStatus.h"
#include ".\Status\AbsorbStatus.h"
#include ".\Status\BlindStatus.h"
#include ".\Status\BonusDamageStatus.h"

#include ".\Status\ChaosStatus.h"
#include ".\Status\CureStatus.h"
#include ".\Status\DragonTransStatus.h"

#include ".\Status\FearStatus.h"
#include ".\Status\IncompetenceStatus.h"

#include ".\Status\LowHPStatus.h"
#include ".\Status\MagicShieldStatus.h"
#include ".\Status\MirrorStatus.h"
#include ".\Status\SleepStatus.h"
#include ".\Status\SPBonusStatus.h"
#include ".\Status\StunStatus.h"


#include ".\Status\ThrustStatus.h"


#include ".\Status\WindShieldStatus.h"
#include ".\Status\WoundStatus.h"

#include ".\Status\EtcStatus.h"
#include ".\Status\RecoverStatus.h"


#include ".\Status\StyleDown.h"
#include ".\Status\StyleStun.h"
#include ".\Status\StyleThrust.h"
#include ".\DelayedSkill.h"
#include ".\InstantSkill.h"
#include ".\NormalAreaAttack.h"
#include ".\NormalAttack.h"
#include ".\PassiveSkill.h"
#include ".\Skill.h"
#include ".\Skill_Info.h"
#include ".\SkillFactory.h"
#include ".\SkillManager.h"
#include ".\SkillSlotManager.h"
#include ".\StyleSkill.h"
#include ".\SkillSystem\CSSyncTuner.h"
#include ".\SkillSystem\PerkManager.h"
#include ".\MultiplyExpFormula.h"
#include ".\NumericEngine.h"
#include ".\CharacterFormula.h"
#include ".\NPCAttrForUpdate.h"
#include ".\PlayerAttrForUpdate.h"
#include ".\GameDominationManager.h"
#include ".\GameGuild.h"
#include ".\GameGuild.SendPacket.h"
#include ".\GameGuildCommon.h"
#include ".\GameGuildExtension.h"
#include ".\GameGuildManager.h"
#include ".\GameGuildMember.h"
#include ".\GameGuildRelation.h"
#include ".\GMCmdManager.h"
#include ".\GMCmdString.h"
#include ".\GameLog.h"
#include ".\EventManager.h"
#include ".\PeakTimeEvent.h"
#include ".\PlayerEventManager.h"
#include ".\AreaConquestCommonHeader.h"
#include ".\AchievementManager.h"
#include ".\QuestAction_Concrete.h"
#include ".\QuestCondition_Concrete.h"
#include ".\QuestInfoManagerEx.h"
#include ".\QuestManager_Concrete.h"
#include ".\Fatigue.h"
#include ".\FatigueManager.h"
#include ".\ChaoState.h"
#include ".\FieldPvP.h"
#include ".\GameScriptParserManager.h"
#include ".\Npcai\BattleRecord.h"
#include ".\ItemExpDistributor.h"
#include ".\Party\GameParty.h"
#include ".\Party\GamePartyManager.h"
#include ".\Party\GamePartyState.h"
#include ".\GameParty\GamePartyOperator.h"
#include ".\GameParty\NewGameParty.h"
#include ".\GameParty\NewGamePartyManager.h"
#include ".\FriendInvitation\FriendInvitationRecallProc.h"
#include ".\FriendInvitation\FriendInvitationReWardProc.h"
#include ".\FriendInvitation\GFriendInvitationController.h"
#include ".\FriendInvitation\InvitateFriendInfo.h"
#include ".\AccumulatePoint.h"

//==================================================================================================
//#include "./waverix_game_externs.hpp"
#endif //WAVERIX_PCH_BUILD_SELECT
#endif //WAVERIX_USING_PCH_LIST