// sun
//

#define SUN_KR_GAMEID					0x000a0100
#define SUN_KR_DEFAULT					(SUN_KR_GAMEID + 0)			// 디폴트 서버
#define SUN_KR_DEV						(SUN_KR_GAMEID + 1)			// 개발망 테스트 서버
#define SUN_KR_INTRA					(SUN_KR_GAMEID + 2)			// 사내용 테스트 서버
#define SUN_KR_LIVE						(SUN_KR_GAMEID + 3)			// 라이브 서버

#define SUN_CN_GAMEID					0x000a0200
#define SUN_CN_DEFAULT					(SUN_CN_GAMEID + 0)			// 디폴트 서버
#define SUN_CN_GAMEID_01				(SUN_CN_GAMEID + 1)			// cn1.sun.the9.com
#define SUN_CN_GAMEID_02				(SUN_CN_GAMEID + 2)			// cn2.sun.the9.com
#define SUN_CN_GAMEID_03				(SUN_CN_GAMEID + 3)			// cn3.sun.the9.com
#define SUN_CN_GAMEID_04				(SUN_CN_GAMEID + 4)			// cn4.sun.the9.com
#define SUN_CN_GAMEID_05				(SUN_CN_GAMEID + 5)			// cn5.sun.the9.com
#define SUN_CN_GAMEID_06				(SUN_CN_GAMEID + 6)			// cn6.sun.the9.com
#define SUN_CN_IBT						(SUN_CN_GAMEID + 20)		// 172.18.253.15
#define SUN_CN_KRTEST					(SUN_CN_GAMEID + 21)		// 본사 중국테섭
#define SUN_CN_LIVETEST					(SUN_CN_GAMEID + 22)		// unknown

#define SUN_TW_GAMEID					0x000a0300					 
#define SUN_TW_DEFAULT					(SUN_TW_GAMEID + 0)			// 디폴트 서버
#define SUN_TW_LIVETEST					(SUN_TW_GAMEID + 1)			// 라이브테스트 서버
#define SUN_TW_LIVE						(SUN_TW_GAMEID + 2)			// 라이브 서버
#define SUN_TW_IBT						(SUN_TW_GAMEID + 20)		// 
#define SUN_TW_KRTEST					(SUN_TW_GAMEID + 21)		// 본사 대만테섭
