#pragma once



#define MAX_GUIDANCE_PARTY_NUM			8		// 가이던스에 속한 최대 파티 개수
#define MAX_GUIDANCE_MEMBER_NUM			80		// 가이던스에 속한 최대 멤버 수

#define PARTY_MASTER_SUMMON_AROUND_DIST 2		// 파티장 근처 소환 거리

enum eGUIDANCE_TYPE
{
	eGUIDANCE_NORMAL,
	eGUIDANCE_MAX
};

enum eITEM_DISTRIBUTION_TYPE
{
	eITEM_DISTRIBUTION_DEFAULT,				//자유획득(기본값)
	eITEM_DISTRIBUTION_FIFO_PRIORITY,		//차례대로 획득(방장부터..)
	eITEM_DISTRIBUTION_MASTER_PRIORITY,		//파티장이 획득
	eITEM_DISTRIBUTION_RANDOM,				//램덤획득
	eITEM_DISTRIBUTION_CLASS_PRIORITY,		//착용자 우선 랜덤 획득
    eITEM_DISTRIBUTION_DICE_AND_DEFAULT,    //주사위 자유 획득 방식     _NA_003033_20110831_DICECAST_ITEM_ROUTING
    eITEM_DISTRIBUTION_DICE_AND_FIFO,       //주사위 차례대로 획득 방식 _NA_003033_20110831_DICECAST_ITEM_ROUTING
	eITEM_DISTRIBUTION_MAX,
};

enum 
{
    eITEM_DISTRIBUTION_MAX_DICE_BEFORE = eITEM_DISTRIBUTION_DICE_AND_DEFAULT,
};