#ifndef __SOLARQUEST_QUESTACTIONINFO_CONCRETE_H
#define __SOLARQUEST_QUESTACTIONINFO_CONCRETE_H
#pragma once

#include "QuestActionInfo.h"



BEGIN_DECL_QACTION_INFO( QUEST_ACTION_ITEM )
	enum { _DEF_CHECK_NUM=3, _MAX_CHECK_NUM=5, };		//< 수락행동 아이템제거는 3, 완료행동 아이템제거는5
	__BOOL_PROPERTY( Delete )							//< 아이템 삭제 여부(TRUE) : 부여(FALSE)
	__PROPERTY( BYTE, ItemArrayCount )					//< 존재하는 아이템 개수
	__ARRAY_PROPERTY( WORD, _MAX_CHECK_NUM, ItemCode )
	__ARRAY_PROPERTY( BYTE, _MAX_CHECK_NUM, ItemNum )
END_DECL_QACTION_INFO
//
//BEGIN_DECL_QACTION_INFO( QUEST_ACTION_TIMER )
//	__PROPERTY( DWORD, ExpiredTime );
//END_DECL_QACTION_INFO

BEGIN_DECL_QACTION_INFO( QUEST_ACTION_CHANGEofCLASS )	// Condition을 통해 캐릭터 제약, 레벨등등이 필터링 되었을 터...
	PROPERTY<eSPECIAL_QUEST_REWARD>		ChangeOfClassStep;			// x차 전직 (RewardInfo::eSPECIAL_REWARD)
END_DECL_QACTION_INFO

// 퀘스트 수락시 몬스터 소환.
BEGIN_DECL_QACTION_INFO( QUEST_ACTION_SPAWN_MONSTER )
	__PROPERTY( DWORD, HideNpcCode )								//< 숨겨야할 NPC코드.
	__PROPERTY( DWORD, SummonMonsterCode )							//< 소환할 몬스터 코드
END_DECL_QACTION_INFO

BEGIN_DECL_QACTION_INFO(QUEST_ACTION_SPAWN_MONSTER_ABANDON)
END_DECL_QACTION_INFO

// Create Portal (goto Mission) On Quest Accept
BEGIN_DECL_QACTION_INFO(QUEST_ACTION_CREATE_PORTAL)
    __PROPERTY(MAPCODE, MapPortalCode)  //< 해당 맵으로 가기 위한 포탈 생성
END_DECL_QACTION_INFO

BEGIN_DECL_QACTION_INFO(QUEST_ACTION_CLOSE_PORTAL)
END_DECL_QACTION_INFO

// 퀘스트 완료,포기시 진행중 채집물 초기화
BEGIN_DECL_QACTION_INFO(QUEST_ACTION_DELETE_COLLECTIONID)
END_DECL_QACTION_INFO

#ifdef _NA_003027_20111013_HONOR_SYSTEM
BEGIN_DECL_QACTION_INFO(QUEST_ACTION_DAILY_QUEST)
END_DECL_QACTION_INFO

BEGIN_DECL_QACTION_INFO(QUEST_ACTION_DAILY_QUEST_DELETE)
END_DECL_QACTION_INFO
#endif //_NA_003027_20111013_HONOR_SYSTEM

#endif
