#pragma once

#include "AuthenticateUserResponse.h"
#include "AuthenticateUserRequest.h"
#include "StopUsingStatusResponse.h"
#include "StopUsingStatusRequest.h"
#include "StartUsingStatusResponse.h"
#include "StartUsingStatusRequest.h"
#include "KeepUsingStatusResponse.h"
#include "KeepUsingStatusRequest.h"
#include "GetUserInfoResponse.h"
#include "GetUserInfoRequest.h"
#include "BuyStatusRequest.h"
#include "GetMoneyBalanceRequest.h"
#include "GetMoneyBalanceResponse.h"
#include "BuyStatusResponse.h"
#include "BuyGameItemRequest.h"
#include "BuyGameItemResponse.h"
