#ifndef __PROTOCOL_DW_H__
#define __PROTOCOL_DW_H__

//-------------------------------------------------------------------------------------------------------
// *  Prefix
//		C : Client
//		G : Game Server
//		M : Master Server
//		D : DBP Server
//
// * Postfix
//		SYN - Server에 요청
//		ACK - 요청에 대한 허락
//		NAK - 요청에 대한 거부
//		CMD - Server의 명령
//		BRD - Server가 동기화 관련 내용을 알림
//		DBR - DBProxy에서만 사용함!
//
// * 프로토콜 Naming Rule
//		Prefix_카테고리명_프로토콜명_Postfix
//		ex) CG_CONNECTION_REGISTER_SYN
//
//-------------------------------------------------------------------------------------------------------

/// 카테고리
enum eDW_CATEGORY
{
	DW_CONNECTION		= 150,  // (WAVERIX) (WARNING) 서버간 카테고리 시작 번호 주의할 것.
	DW_FRIEND,
	DW_GM,
	DW_CHAO,
	DW_MEMO,
	DW_STATUS,
	DW_GUILD,
//#ifdef _NA_0_20080612_WORLDSERVER_REFACTORING
	DW_COMMUNITY,
//#endif
    DW_GROUP,   // __KR_001355_20090608_GROUPINGSYSTEM_DW 그룹 맺기 시스템 관련
    DW_LOTTO,   // __NA_001359_20090619_HEIM_LOTTO_SYSTEM 하임 로또 시스템 관련
    WZ_GUILD, // CHANGES: f110518.2L
#ifdef _NA_008283_20150511_NOTIFICATIONS_SYSTEM
    DW_NOTIFICATION,
#endif // _NA_008283_20150511_NOTIFICATIONS_SYSTEM

	DW_MAX,
};


/// 프로토콜
enum eDW_CONNECTION_PROTOCOL
{
	DW_CONNECTION_SERVER_INFO_CMD,
    DW_CONNECTION_GROUND_CMD, // NOTE: f110617.1L
};

enum eDW_FRIEND_PROTOCOL
{
	DW_FRIEND_GETLIST_SYN,		// 친구 목록
	DW_FRIEND_GETLIST_DBR,
	DW_FRIEND_GETLIST_ACK,
	DW_FRIEND_GETLIST_NAK,
	DW_FRIEND_ADD_SYN,			// A->B add friend
	DW_FRIEND_ADD_DBR,
	DW_FRIEND_ADD_ACK,
	DW_FRIEND_ADD_NAK,
	DW_FRIEND_DEL_SYN,			// 친구 삭제
	DW_FRIEND_DEL_DBR,
	DW_FRIEND_DEL_ACK,
	DW_FRIEND_DEL_NAK,
	DW_FRIEND_BLOCK_SYN,		// 유저 차단
	DW_FRIEND_BLOCK_DBR,
	DW_FRIEND_BLOCK_ACK,
	DW_FRIEND_BLOCK_NAK,
	DW_FRIEND_BLOCK_FREE_SYN,	// 차단 삭제
	DW_FRIEND_BLOCK_FREE_DBR,
	DW_FRIEND_BLOCK_FREE_ACK,
	DW_FRIEND_BLOCK_FREE_NAK,
    //_KR_0_20091021_FIRENDINVITATION_EXTEND = {
	DW_FRIEND_INVITATIONRELATION_FREE_CMD, //친구 추천 관계 해제, 리턴은 필요 없네요~
	DW_FRIEND_INVITATIONRELATION_FREE_DBR,   
    DW_FRIEND_INVITATIONRELATION_REWARDINSERT_CMD, //친구 보상 아이템 목록 추가, 리턴은 필요 없어요~
    DW_FRIEND_INVITATIONRELATION_REWARDINSERT_DBR,   
    //}
    //_NA_0_20100527_ADD_CHAR_RELATION_MEMO
    DW_FRIEND_DETAIL_INFO_SYN,
    DW_FRIEND_DATAIL_INFO_DBR,
    DW_FRIEND_DETAIL_INFO_ACK,
    DW_FRIEND_DETAIL_INFO_NAK,
    DW_FRIEND_MEMO_UPDATE_SYN,
    DW_FRIEND_MEMO_UPDATE_DBR,
    DW_FRIEND_MEMO_UPDATE_ACK,
    DW_FRIEND_MEMO_UPDATE_NAK,
};

enum eDW_GM_PROTOCOL
{
	DW_GM_CHATBLOCK_SYN,		// 채팅금지
	DW_GM_CHATBLOCK_DBR,
	DW_GM_CHATBLOCK_ACK,
	DW_GM_CHATBLOCK_NAK,
	DW_GM_CHATALLOW_SYN,		// 채팅허용
	DW_GM_CHATALLOW_DBR,
	DW_GM_CHATALLOW_ACK,
	DW_GM_CHATALLOW_NAK,
	DW_GM_CHATBLOCK_UPDATE_SYN,	// 채팅금지 시간 차감
	DW_GM_CHATBLOCK_UPDATE_DBR,
//	DW_GM_CHATBLOCK_UPDATE_ACK,	// 응답 필요없다
	DW_GM_CHATBLOCK_UPDATE_NAK,
	DW_GM_CHATBLOCKTIME_REQ,	// 채팅금지 시간 요청(처음 접속할 때)
	DW_GM_CHATBLOCKTIME_DBR,
	DW_GM_CHATBLOCKTIME_ANS,
	DW_GM_CHATBLOCKTIME_NAK,
};

// 무단 PK 관련 프로토콜들
enum eDW_CHAO_PROTOCOL
{
	DW_CHAO_ADD_REVENGE_CHAR_SYN,		// 리벤지(나쁜친구) 리스트 등록 요청
	DW_CHAO_ADD_REVENGE_CHAR_DBR,
	DW_CHAO_ADD_REVENGE_CHAR_ACK,
	DW_CHAO_ADD_REVENGE_CHAR_NAK,

	DW_CHAO_REMOVE_REVENGE_CHAR_SYN,	// 리벤지 리스트에서 삭제 요청(C->W->D)
	DW_CHAO_REMOVE_REVENGE_CHAR_DBR,
	DW_CHAO_REMOVE_REVENGE_CHAR_ACK,
	DW_CHAO_REMOVE_REVENGE_CHAR_NAK,

	DW_CHAO_PK_REVENGE_CHAR_SYN,		// 리벤지 성공하여 리스트에서 삭제 요청(G->A->W->D)
	DW_CHAO_PK_REVENGE_CHAR_DBR,
	DW_CHAO_PK_REVENGE_CHAR_ACK,
	DW_CHAO_PK_REVENGE_CHAR_NAK,
};

enum eDW_MEMO_PROTOCOL
{
	DW_MEMO_SEND_SYN,
	DW_MEMO_SEND_DBR,
	DW_MEMO_SEND_ACK,
	DW_MEMO_SEND_NAK,

	DW_MEMO_LIST_REQ,
	DW_MEMO_LIST_DBR,
	DW_MEMO_LIST_ANS,
	DW_MEMO_LIST_NAK,

	DW_MEMO_VIEW_REQ,
	DW_MEMO_VIEW_DBR,
	DW_MEMO_VIEW_ANS,
	DW_MEMO_VIEW_NAK,

	DW_MEMO_DELETE_SYN,
	DW_MEMO_DELETE_DBR,
	DW_MEMO_DELETE_ACK,
	DW_MEMO_DELETE_NAK,
    //{__NA001254_20090109_RTTG_FUNC_ADD		
	DW_MULTIMEMO_SEND_SYN,
	DW_MULTIMEMO_SEND_DBR,
	DW_MULTIMEMO_SEND_ACK,
    //}
};

enum eDW_STATUS_PROTOCOL
{
	DW_STATUS_INTERCEPTION_REQ,
	DW_STATUS_INTERCEPTION_ANS,
	DW_STATUS_INTERCEPTION_DBR,
	DW_STATUS_INTERCEPTION_NAK,
};

enum eDW_GUILD_PROTOCOL
{
	DW_GUILD_WAREHOUSE_LOGLIST_REQ,
	DW_GUILD_WAREHOUSE_LOGLIST_DBR,
	DW_GUILD_WAREHOUSE_LOGLIST_ANS,
	DW_GUILD_WAREHOUSE_LOGLIST_NAK,

	DW_GUILD_SELECT_NOTICE_SYN,
	DW_GUILD_SELECT_NOTICE_ACK,
	DW_GUILD_SELECT_NOTICE_DBR,
	DW_GUILD_SELECT_NOTICE_NAK,


    //지역점령전 보상/환급 내역 확인 관련 패킷
    //_KR_001385_20091202_DOMINATION_RETURN_HEIM
    DW_DOMINATION_FINDMONEY_SYN,
    DW_DOMINATION_FINDMONEY_ACK,
    DW_DOMINATION_FINDMONEY_DBR,
};

//#ifdef _NA_0_20080612_WORLDSERVER_REFACTORING
enum eDW_COMMUNITY
{
	DW_COMMUNITY_INFO_SYN,
	DW_COMMUNITY_INFO_DBR,
	DW_COMMUNITY_INFO_ANS,
	DW_COMMUNITY_INFO_NAK,
	DW_COMMUNITY_MYLIST_SYN,
	DW_COMMUNITY_MYLIST_ACK,
	DW_COMMUNITY_MYLIST_NAK,
	DW_COMMUNITY_MYLIST_DBR,
	DW_COMMUNITY_CONTACT_ME_ACK, //나를 등록한 커뮤니티 멤버
	DW_COMMUNITY_CONTACT_ME_DBR,
};
//#endif

// __KR_001355_20090608_GROUPINGSYSTEM_DW//그룹맺기 시스템
enum eDW_GROUP
{
	DW_GROUP_ADD_SYN,//그룹 맴버 추가 
	DW_GROUP_ADD_DBR,
	DW_GROUP_ADD_NAK,
	DW_GROUP_ADD_ACK,

	DW_GROUP_DEL_SYN,//그룹 맴버 삭제
	DW_GROUP_DEL_DBR,
	DW_GROUP_DEL_NAK,
	DW_GROUP_DEL_ACK,

  	DW_GROUP_LIST_REQ,//그룹 리스트 요청
	DW_GROUP_LIST_DBR,
	DW_GROUP_LIST_ACK,

    DW_GROUP_ACCUMEXP_CMD,//경험치 축적 요청 
    DW_GROUP_ACCUMEXP_DBR,

    DW_GROUP_SET_MEMBERINFO_CMD,//그룹 맴버 정보 세팅

    DW_GROUP_INIT_ACCUMEXP_CMD,
    DW_GROUP_INIT_ACCUMEXP_DBR,
};

// used by __NA_001359_20090619_HEIM_LOTTO_SYSTEM
enum eDW_LOTTO
{
    DW_LOTTO_LOAD_ENTRY_SYN,            // 하임 로또 응모 내역 로딩 요청
    DW_LOTTO_LOAD_ENTRY_DBR,
    DW_LOTTO_LOAD_ENTRY_ACK,            // 하임 로또 응모 내역 로딩 응답
    DW_LOTTO_LOAD_SYN,                  // 하임 로또 정보 로딩 요청
    DW_LOTTO_LOAD_DBR,
    DW_LOTTO_LOAD_ACK,                  // 하임 로또 정보 로딩 응답
    DW_LOTTO_WINNER_LIST_SYN,           // 하임 로또 당첨자 목록 로딩 요청
    DW_LOTTO_WINNER_LIST_DBR,
    DW_LOTTO_WINNER_LIST_ACK,           // 하임 로또 당첨자 목록 로딩 응답
    DW_LOTTO_SAVE_ENTRY_SYN,            // 하임 로또 응모 처리 요청
    DW_LOTTO_SAVE_ENTRY_DBR,
    DW_LOTTO_SAVE_ENTRY_ACK,            // 하임 로또 응모 처리 응답
    DW_LOTTO_ROLLOVER_SYN,              // 하임 로또 추첨 및 이월 처리 요청
    DW_LOTTO_ROLLOVER_DBR,
    DW_LOTTO_ROLLOVER_ACK,              // 하임 로또 추첨 및 이월 처리 응답
    DW_LOTTO_ACCUM_NTF,                 // 하임 로또 총 적립액 갱신 통보
    DW_LOTTO_ACCUM_DBR,
    DW_LOTTO_ADD_TICKET_SYN,            // 하임 로또 복권 용지 수 증가 요청
    DW_LOTTO_ADD_TICKET_DBR,
    DW_LOTTO_ADD_TICKET_ACK,            // 하임 로또 복권 용지 수 증가 응답
    DW_LOTTO_REWARD_SYN,                // 하임 로또 당첨금 지급 요청
    DW_LOTTO_REWARD_DBR,
    DW_LOTTO_REWARD_ACK,                // 하임 로또 당첨금 지급 응답
    DW_LOTTO_NOTICE_LIST_SYN,           // 하임 로또 당첨안내 쪽지 목록 로딩 요청
    DW_LOTTO_NOTICE_LIST_DBR,
    DW_LOTTO_NOTICE_LIST_ACK,           // 하임 로또 당첨안내 쪽지 목록 로딩 응답
    DW_LOTTO_NOTICE_DEL_SYN,            // 하임 로또 당첨안내 쪽지 삭제 요청
    DW_LOTTO_NOTICE_DEL_DBR,
    DW_LOTTO_NOTICE_DEL_ACK,            // 하임 로또 당첨안내 쪽지 삭제 응답
    DW_LOTTO_PAYMENT_UPDATE_NTF,        // 캐릭터 유효 소비 하임 액수 저장
    DW_LOTTO_PAYMENT_UPDATE_DBR,
};

//_NA002635_GZ_DZ_PROTOCOL_UINIFICATION

/// 프로토콜
enum eWZ_GUILD_PROTOCOL
{
	// 길드 관리
	//WZ_GUILD_CREATE_GUILD_CMD,
	WZ_GUILD_DESTROY_GUILD_CMD,
	WZ_GUILD_JOIN_GUILD_CMD,
	WZ_GUILD_WITHDRAW_GUILD_CMD,

	WZ_GUILD_NOTICE_CMD,
	// 길드 멤버 상태
	WZ_GUILD_LOGIN_CHAR_CMD,

    //__NA_000000_20070528_TAIWAN_GUILD_PVP
	WZ_GUILD_CHUNTING_PVP_RESULT_CMD,

	WZ_GUILD_CHANGE_DUTY_CMD,
	WZ_GUILD_CHANGE_MASTER_CMD,

	WZ_GUILD_CHANGE_COMMANDER_CMD,
	WZ_GUILD_CHANGE_CORPS_CMD,
	WZ_GUILD_CREATE_REAR_CAMP_CMD,
	WZ_GUILD_DESTROY_REAR_CAMP_CMD,
	WZ_GUILD_CREATE_CMD,
	WZ_GUILD_RESTORE_SYN,
	WZ_GUILD_RESTORE_ACK,
	WZ_GUILD_RESTORE_NAK,
	WZ_GUILD_KICK_PLAYER_CMD,
	WZ_GUILD_LOGOUT_CHAR_CMD,
	WZ_GUILD_MEMBER_INFO_REQ_SYN,
	WZ_GUILD_MEMBER_INFO_REQ_ACK,

	WZ_GUILD_DESTROY_WAIT_CMD,
	WZ_GUILD_RECOVERY_GUILD_CMD,

    WZ_GUILD_GUILDMARK_REGISTER_CMD,
	WZ_GUILD_GUILDMARK_DELETE_CMD,

    WZ_GUILD_WAREHOUSE_OPEN_CMD,
	WZ_GUILD_WAREHOUSE_CLOSE_CMD,

	WZ_GUILD_CHANGE_NOTICE_SYN,
	WZ_GUILD_CHANGE_NOTICE_CMD,
	WZ_GUILD_CHANGE_NOTICE_NAK,
    // __NA000000_20081106_GUILD_NAME_CHANGE
	WZ_GUILD_NAME_CHANGE_CMD,
    //_KR_001385_20091202_DOMINATION_RETURN_HEIM
    WZ_GUILD_DOMINATION_RETURNHIME_CMD,
    WZ_GUILD_DOMINATION_RETURNHIME_ACK,

    //_NA_0_20100527_ADD_CHAR_RELATION_MEMO
    WZ_GUILD_CHECK_CONDITION_ACCESS_DETAIL_INFO_SYN,
    WZ_GUILD_CHECK_CONDITION_ACCESS_DETAIL_INFO_ACK,
    WZ_GUILD_CHECK_CONDITION_ACCESS_DETAIL_INFO_NAK,

    WZ_GUILD_RENAME_CHAR_CMD,
}; //end of 'eWZ_GUILD_PROTOCOL'

#ifdef _NA_008283_20150511_NOTIFICATIONS_SYSTEM
enum eDW_NOTIFICATION_PROTOCOL
{
    DW_NOTIFICATION_ITEM_SYN,
    DW_NOTIFICATION_CLEAR_SYN,
};
#endif // _NA_008283_20150511_NOTIFICATIONS_SYSTEM

#endif // __PROTOCOL_DW_H__
