#pragma once

// CHANGES: f110914.1L, change the category index, based on _NA000000_CW_PROTOCOL_UNIFICATION
/// 카테고리
enum eAW_CATEGORY
{
    AW_CONNECTION           = CATEGORY_GENERATOR_213,
    AW_USER_STATUS          = CATEGORY_GENERATOR_214,
    AW_PARTY                = CATEGORY_GENERATOR_215,
    AW_GM                   = CATEGORY_GENERATOR_216,
    AW_CHAO                 = CATEGORY_GENERATOR_217,
    AW_ITEM                 = CATEGORY_GENERATOR_218,
    //__NA000941_080204_TASK_SURVIVAL_SOLOING_QUEST_SYSTEM__ : 타락한 사원
    // (주석 처리되어 있던 것 재 활성화 기존 프로토콜 위반되지 않도록 뒤로 이동 AW_MAX는 참조되는 곳 없었음)
    AW_OPERATION            = CATEGORY_GENERATOR_219,
    AW_FRIENDINVITATE       = CATEGORY_GENERATOR_220, //_KR_0_20091021_FIRENDINVITATION_EXTEND
    //
    AW_MAX                  = CATEGORY_GENERATOR_211,
};

// used by _KR_0_20091021_FIRENDINVITATION_EXTEND
enum eAW_FRIENDINVITATE_PROTOCOL		//친구 초대 이벤트
{
	AW_FRIENDINVITATE_INVITATELIST_CMD		=1,	//W->A 내가 초대한 캐릭터 목록	
    AW_FRIEND_INVITATIONR_INSERT_CMD,           //D->A->W 추천한 친구가 캐릭터 생성했을때
};

/// 프로토콜
enum eAW_CONNECTION_PROTOCOL
{
	AW_AGENTSERVER_INFO_SYN		= 1,

	AW_PREPARE_NEW_USER_SYN,
	AW_PREPARE_NEW_USER_ACK,
	AW_PREPARE_NEW_USER_NAK,

	AW_ABUSING_USER_VERIFY_QUERY_CMD,
    AW_CONNECTION_GROUND_CMD, // NOTE: f110617.1L
    AW_CONNECTION_PACKET_BROADCASTER_ONEtoN_SYN, // NOTE: f110727.1L
};

enum eAW_USER_STATUS_PROTOCOL
{
	AW_USER_SET_CHARNAME_SYN	= 1,
	AW_USER_UNSET_CHARNAME_SYN,
	AW_USER_ENTER_ZONE_SYN,
	AW_USER_LEAVE_ZONE_SYN,
	AW_USER_LOGOUT,
	AW_USER_RESTORE_SYN,				// 월드 서버에 목록 복구 요청
	AW_USER_RESTORE_CMD,				// 현재 접속된 사용자 목록
	AW_USER_LEVELUP_CMD,				// 사용자 레벨업
	AW_USER_STATUS_INTERCEPTION_SYN,
	AW_USER_STATUS_INTERCEPTION_ACK,
	AW_USER_STATUS_INTERCEPTION_NAK,
    //__NA_0_20090627_HEIM_ACQUISITION_S2S_NOTIFICATION
    AW_USER_STATUS_HEIM_ACQUISITION_NTF, // 하임 획득 통지
    //__NA_0_20090627_HEIM_CONSUMPTION_S2S_NOTIFICATION
    AW_USER_STATUS_HEIM_CONSUMPTION_NTF, // 하임 소비 통지
    //__KR_001355_20090608_GROUPINGSYSTEM_GW
    AW_STATUS_GROUP_SET_MEMBERINFO_CMD,    //그룹 멤버 정보 세팅
    AW_STATUS_GROUP_EXP_ACQUISITION_CMD,    //경험치 획득 통지
    AW_STATUS_GROUP_ADDEXP_CMD,             //경험치 추가 요청
    AW_STATUS_GROUP_ADDMONEY_CMD,           //하임 추가 요청
    AW_STATUS_GROUP_START_CMD,              //그룹 시스템 세팅 시작
    //__NA_001359_20090619_HEIM_LOTTO_SYSTEM
    AW_USER_LOTTO_REWARD_SYN,               // 하임 로또 상금 지급 요청
    AW_USER_LOTTO_REWARD_ACK,               // 하임 로또 상금 지급 응답
    //__NA_001359_20090619_HEIM_LOTTO_SYSTEM && _NA_0_20100115_HEIM_LOTTO_TICKET_PURCHASE
    AW_USER_LOTTO_TICKET_PURCHASE_SYN,      // 하임 로또 복권용지 직접 구입 요청
    AW_USER_LOTTO_TICKET_PURCHASE_ACK,      // 하임 로또 복권용지 직접 구입 응답
    //_PCBANG_POLICY_CHANGE_POST_EXPIRED
    AW_USER_STATUS_PCBANG_BILLING_NTF,      // PC방 빌링 정보 변환
    //_KR_001385_20091202_DOMINATION_RETURN_HEIM
    AW_USER_DOMINATION_RETURNHIEM_CMD,      // 지역 점령전 경매 금액 돌려 받기
    //_NA_20100812_INTEGRATE_SYSTEM_MEMO_DOMINATION 
    AW_USER_SYSTEMMEMO_SEND_CMD,            // 시스템 쪽지 요청
    //_NA002676_WORLD_SERVER_RENEWAL
    AW_USER_STADING_POSITION_CMD,
};

enum eAW_PARTY_PROTOCOL
{
	AW_PARTY_MAKE_SYN	= 1,			// 파티 개설
	AW_PARTY_JOIN_MEMBER_SYN,			// 파티 가입
	AW_PARTY_WITHDRAW_MEMBER_SYN,		// 파티 탈퇴
	AW_PARTY_DESTROY_SYN,				// 파티 해체
    AW_PARTY_CHANGE_MASTER_SYN,         // 파티장 변경
    AW_PARTY_FINDING_JOIN_SYN,          // 파티 모집에 속한 파티 참가 요청
    AW_PARTY_FINDING_JOIN_RESULT_ACK,   // 파티 모집에 속한 파티 참가 요청에 대한 처리 결과 응답
    AW_PARTY_ROOM_KEY_SYN,              // 배틀존 파티시 방번호 설정
};

enum eAW_GM_PROTOCOL
{
	AW_GM_WHISPER_SET_CMD	= 1,		// 귓말 켬/끔
	AW_GM_USERCHAT_BLOCK_CMD,			// 채팅 금지/허용
	AW_GM_NOTICE_CMD,					// 공지

    // __NA_001359_20090619_HEIM_LOTTO_SYSTEM
    AW_GM_LOTTO_NUM_CMD,                // 하임 로또 현재 회차 당첨 번호 보이기 명령
    AW_GM_LOTTO_SETTLE_CMD,             // 하임 로또 강제 추첨 명령
    AW_GM_LOTTO_FUND_CMD,               // 하임 로또 기금 적립 명령
};

enum eAW_CHAO_PROTOCOL
{
	AW_CHAO_REQUEST_REVENGEINFO_SYN = 1,	// 리벤지 정보 요청(A->W)
	AW_CHAO_REQUEST_REVENGEINFO_ACK,		// 리벤지 정보(W->A)
	AW_CHAO_REQUEST_REVENGEINFO_NAK,		// 리벤지 정보 전송 실패(W->A)

	AW_CHAO_REMOVE_REVENGE_CHAR_CMD,		// 리벤지 대상 삭제(클라이언트가 삭제했을 때)(W->A)

	AW_CHAO_REMOVE_REVENGE_CHAR_SYN,		// 리벤지 대상 한명 제거(PK를 통해 제거했을 때)(A->W)
	AW_CHAO_REMOVE_REVENGE_CHAR_ACK,		// 리벤지 대상 한명 제거 성공(W->A)
	AW_CHAO_REMOVE_REVENGE_CHAR_NAK,		// 리벤지 대상 한명 제거 실패(W->A)

	AW_CHAO_ADD_REVENGE_CHAR_SYN,			// 리벤지 대상 추가 요청(A->W)
	AW_CHAO_ADD_REVENGE_CHAR_ACK,			// 리벤지 대상 추가 성공(W->A)
	AW_CHAO_ADD_REVENGE_CHAR_NAK,			// 리벤지 대상 추가 실패(W->A)
};

enum eAW_ITEM_PROTOCOL
{
	AW_ITEM_CHANGE_SPECIAL_ITEM_OWN_CMD = 1,
	AW_ITEM_CHANGE_SPECIAL_ITEM_SYN,			// 유료 아이템 정보 요청
	AW_ITEM_SPECIAL_ITEM_CLEAR_CMD,
    AW_ITEM_USE_DECREE_ITEM_SYN,				// 해방군의 포고문 사용[중국버젼 1회 사용]	
	AW_ITEM_USE_DECREE_ITEM_ACK,
	AW_ITEM_USE_DECREE_ITEM_NAK,

    // _NA_20101011_HEIM_LOTTO_CASH_TICKET
    AW_ITEM_USE_HEIM_LOTTO_TICKET_SYN,      // 하임행운 캐시 응모권 사용 요청 (A->W)
    AW_ITEM_USE_HEIM_LOTTO_TICKET_ACK,      // 하임행운 캐시 응모권 사용 응답 (W->A)
};


// USERCOUNT_SYN은 월드 서버 자체에서 집계하기로 수정하고, USERMONEY_SYN은 GM으로 옮겼음
/*
enum eAW_USER_OPERATION_PROTOCOL
{
	AW_USERCOUNT_SYN	= 1,
	AW_USERMONEY_SYN,					// 현재 이 서버의 돈
};
*/

enum eAW_OPERATION_PROTOCOL
{
	AW_OPERATION_ROOM_CTRL_CMD		,	//__NA000941_080204_TASK_SURVIVAL_SOLOING_QUEST_SYSTEM__ : 타락한 사원
};
