#ifndef _PACKET_SERVERCOMMON_H_
#define _PACKET_SERVERCOMMON_H_

// 카테고리 0번은 서버 공통 프로토콜로 예약됨

enum eSERVERCOMMON_CATEGORY
{
	SERVERCOMMON = 0,	// CG_CHARINFO = 1 임!
};

enum eSERVERCOMMON_PROTOCOL
{
	SERVERCOMMON_SERVERTYPE,
	SERVERCOMMON_HEARTBEAT,
	SERVERCOMMON_SERVERSHUTDOWN_REQ,
	SERVERCOMMON_SERVERSHUTDOWN_ANS,

	SERVERCOMMON_DATA_TRANSFER_PLZ_GIVEME_DATA_SYN,
	SERVERCOMMON_DATA_TRANSFER_PLZ_GIVEME_DATA_ACK,
	SERVERCOMMON_DATA_TRANSFER_PLZ_GIVEME_DATA_NAK,
	SERVERCOMMON_DATA_TRANSFER_SENDDATA_CMD,
	SERVERCOMMON_DATA_TRANSFER_SENDDATA_ACK,
	SERVERCOMMON_DATA_TRANSFER_SENDDATA_NAK,
	SERVERCOMMON_DATA_TRANSFER_SENDDATA_NTF,

	SERVERCOMMON_SECURE_LOG_NTF,
    //__NA000000_SHOP_USERID_50_PASSING_PROC__
    SERVERCOMMON_QUERY_CHARINFO_SYN,
    SERVERCOMMON_QUERY_CHARINFO_DBR,
    SERVERCOMMON_QUERY_CHARINFO_ACK,
};



#endif // _PACKET_SERVERCOMMON_H_