#pragma once


/// 카테고리
enum eMW_CATEGORY
{
	MW_CONNECTION			= 1,
	MW_OPERATION,
	MW_ARMORKIT,
};


/// 프로토콜
enum eMW_CONNECTION_PROTOCOL
{
	MW_SERVER_INFO_CMD,

	MW_CONNECTION_DISCONNECT_CMD	= 200,
	MW_CONNECTION_PHASE_SHIFT_CMD	= 201,
	MW_CONNECTION_BLOCK_CMD			= 202,
    MW_CONNECTION_GROUND_CMD, // NOTE: f110617.1L
};

enum eMW_OPERATION_PROTOCOL
{
	MW_NOTICE_CMD,
	MW_GM_LIST_CMD,
	MW_USERCOUNT_SYN,
	MW_USERMONEY_SYN,
	MW_BATTLEZONEINFO_REQ,
	MW_BATTLEZONEINFO_ANS,

//	MW_OPERATION_SERVERSHUTDOWN_REQ,
//	MW_OPERATION_SERVERSHUTDOWN_ANS,
    //{__NA001254_20090109_RTTG_FUNC_ADD
	MW_MULTIMEMO_SEND_SYN,
	MW_MULTIMEMO_SEND_ACK,
    //}
};

enum eMW_ARMORKIT_PROTOCOL
{
	MW_ARMORKIT_FINDHACK_SYN,
};

