#pragma once

#ifndef __SCRIPTCODE_DEFINITION_H
#define __SCRIPTCODE_DEFINITION_H

#ifndef  __NA_000252_20070208_VERSION_GMCMD

	#include <ScriptCode.IParser.h>

	#define SCRIPT_CODE_DEFINITION( name, value )	\
		static const SCRIPT_CODE_T cSCRIPT_CODE_##name	= value

	#define SCRIPT_CODE_KEY( name )	sSCRIPT_CODE::cSCRIPT_CODE_##name

	struct sSCRIPT_CODE
	{
		SCRIPT_CODE_DEFINITION(	EMPTY,			0);					// Control Flag
		SCRIPT_CODE_DEFINITION(	SCRIPT_ALL,		1);					// Control Flag
		SCRIPT_CODE_DEFINITION(	NOTIFY_SIGNAL,	2);					// Control Flag
		SCRIPT_CODE_DEFINITION(	CONTROL_FLAG_UPPERBOUNDARY,	10);	// Control Flag
		SCRIPT_CODE_DEFINITION(	LIST_SIZE,		100);				// COUNT Flag

		SCRIPT_CODE_DEFINITION(	ACCESSORYITEMINFO	,	10	);
		SCRIPT_CODE_DEFINITION(	ACSCRIPT	,	11	);
		SCRIPT_CODE_DEFINITION(	AICOMMONINFO	,	12	);
		SCRIPT_CODE_DEFINITION(	AITYPEINFO	,	13	);
		SCRIPT_CODE_DEFINITION(	ARMORITEMINFO	,	14	);
		SCRIPT_CODE_DEFINITION(	ARMORTYPEDAMAGEINFO	,	15	);
		SCRIPT_CODE_DEFINITION(	COMPOSITE_NPC	,	16	);
		SCRIPT_CODE_DEFINITION(	DEC1	,	17	);
		SCRIPT_CODE_DEFINITION(	DEC2	,	18	);
		SCRIPT_CODE_DEFINITION(	DEVCOMMAND	,	19	);
		SCRIPT_CODE_DEFINITION(	DROPRATIOINFO	,	20	);
		SCRIPT_CODE_DEFINITION(	ENC1	,	21	);
		SCRIPT_CODE_DEFINITION(	ENC2	,	22	);
		SCRIPT_CODE_DEFINITION(	ENCHANT	,	23	);
		SCRIPT_CODE_DEFINITION(	EXPVALUEINFO	,	24	);
		SCRIPT_CODE_DEFINITION(	EXTRASTONEOPTIONINFO	,	25	);
		SCRIPT_CODE_DEFINITION(	FATIGUEOPTION	,	26	);
		SCRIPT_CODE_DEFINITION(	FIELD	,	27	);
		SCRIPT_CODE_DEFINITION(	FORMULARATIO	,	29	);
		SCRIPT_CODE_DEFINITION(	GMCOMMAND	,	30	);
		SCRIPT_CODE_DEFINITION(	GMLIST	,	31	);
		SCRIPT_CODE_DEFINITION(	GROUP	,	32	);
		SCRIPT_CODE_DEFINITION(	INITCHARINFO	,	33	);
		SCRIPT_CODE_DEFINITION(	INITCHARINFOLIST	,	34	);
		SCRIPT_CODE_DEFINITION(	ITEMCOMPOSELIST	,	35	);
		SCRIPT_CODE_DEFINITION(	ITEMCOMPOSITEINFO	,	36	);
		SCRIPT_CODE_DEFINITION(	ITEMCOMPOSITERESULTINFO	,	37	);
		SCRIPT_CODE_DEFINITION(	ITEMCRYSTALIZELIST	,	38	);
		SCRIPT_CODE_DEFINITION(	ITEMDROPINFO	,	39	);
		SCRIPT_CODE_DEFINITION(	ITEMDROPPERGRADE	,	40	);
		SCRIPT_CODE_DEFINITION(	ITEMTYPEDROPRATIO	,	41	);
		SCRIPT_CODE_DEFINITION(	ITEMTYPELIST	,	42	);
		SCRIPT_CODE_DEFINITION(	LIMITEDMAPPORT	,	43	);
		SCRIPT_CODE_DEFINITION(	MAPENTERANCEPORTAL	,	44	);
		SCRIPT_CODE_DEFINITION(	MATCHINFO	,	45	);
		SCRIPT_CODE_DEFINITION(	MISSIONREWARDINFO	,	46	);
		SCRIPT_CODE_DEFINITION(	NOTICE_SAMPLE	,	47	);
		SCRIPT_CODE_DEFINITION(	NPCEXTRAINFO	,	48	);
		SCRIPT_CODE_DEFINITION(	NPCINFO	,	49	);
		SCRIPT_CODE_DEFINITION(	PKSCRIPT	,	50	);
		SCRIPT_CODE_DEFINITION(	QUESTINFO	,	51	);
		SCRIPT_CODE_DEFINITION(	RANKOPTIONINFO	,	52	);
		SCRIPT_CODE_DEFINITION(	RAREITEMDROPINFO	,	53	);
		SCRIPT_CODE_DEFINITION(	REGEN	,	54	);
		SCRIPT_CODE_DEFINITION(	REGEN_POS	,	55	);
		SCRIPT_CODE_DEFINITION(	REQUIREFIELDLEVELINFO	,	56	);
		SCRIPT_CODE_DEFINITION(	REWARDINFOLIST	,	57	);
		SCRIPT_CODE_DEFINITION(	SHOPINFO	,	58	);
		SCRIPT_CODE_DEFINITION(	SHOUTRANGE	,	59	);
		SCRIPT_CODE_DEFINITION(	SKILLINFO	,	60	);
		SCRIPT_CODE_DEFINITION(	SOCKETOPTIONINFO	,	61	);
		SCRIPT_CODE_DEFINITION(	STATEINFO	,	62	);
		SCRIPT_CODE_DEFINITION(	STYLEINFO	,	63	);
		SCRIPT_CODE_DEFINITION(	STYLEQUICKREGISTINFO	,	64	);
		SCRIPT_CODE_DEFINITION(	SUMMON	,	65	);
		SCRIPT_CODE_DEFINITION(	SUNEVENTINFO	,	66	);
		SCRIPT_CODE_DEFINITION(	SUPERUSERLIST	,	67	);
		SCRIPT_CODE_DEFINITION(	THEMOLAC	,	68	);
		SCRIPT_CODE_DEFINITION(	THEMOLAD	,	69	);
		SCRIPT_CODE_DEFINITION(	THEMOLAS	,	70	);
		SCRIPT_CODE_DEFINITION(	VSHUNTINGREWARDINFO	,	71	);
		SCRIPT_CODE_DEFINITION(	WASTEITEMINFO	,	72	);
		SCRIPT_CODE_DEFINITION(	WEAPONITEMINFO	,	73	);
		SCRIPT_CODE_DEFINITION(	WORLD	,	74	);
		SCRIPT_CODE_DEFINITION(	FIELDWMO	,	75	);
		SCRIPT_CODE_DEFINITION(	FIELDWUT	,	76	);
		SCRIPT_CODE_DEFINITION(	MISSIONRANKINGREWARD	,	77	);
		SCRIPT_CODE_DEFINITION(	MISSIONRANKINGLVAREA	,	78	);
		SCRIPT_CODE_DEFINITION(	CHARGEITEMINFO	,	79	);
		SCRIPT_CODE_DEFINITION(	MONSTERSUMMON	,	80	);

#ifdef __NA_000285_20070220_MAP_PARTIAL_LOADING
		SCRIPT_CODE_DEFINITION(	MAPPARTIALLOADING,	81	);
#endif

#ifdef __NA_000264_20070208_BAN_WORD
		SCRIPT_CODE_DEFINITION(	FILTER,	82 );
		SCRIPT_CODE_DEFINITION(	FILTERNAME,	83 );
#endif

#ifdef __NA_0_20061214_GUILD_SYSTEM_PART2_DUTY
		SCRIPT_CODE_DEFINITION( GUILDRIGHTS, 84 );
		SCRIPT_CODE_DEFINITION( GUILDDUTY, 85 );
#endif

#ifdef _YJ_WORLD_SCRIPT_VER_1_3
		SCRIPT_CODE_DEFINITION( WORLDSUBINFO, 86 );
#endif //
		SCRIPT_CODE_DEFINITION( CURSETOWERTIME, 87 );
		SCRIPT_CODE_DEFINITION( POINTRANKING, 88 );
	};		


#endif //__NA_000252_20070208_VERSION_GMCMD

#endif //__SCRIPTCODE_DEFINITION_H



