//----------------------------------------------------------------------------
/**
	인터페이스 사운드 디파인
*/

enum eUI_SOUND_INDEX
{
	UI_SOUND_DEFAULT_CLICK		= 5,
	UI_SOUND_STATE_UP_CLICK		= 6,
	UI_SOUND_LOGO				= 10,
	UI_SOUND_DROP_BOX			= 20,
	UI_SOUND_DROP_MONEY			= 21,
	UI_SOUND_DEFAULT_WIN_OPEN	= 34,
	UI_SOUND_DEFAULT_WIN_CLOSE	= 35,
	UI_SOUND_MAP_OPEN			= 30, 
	UI_SOUND_MAP_CLOSE			= 31, 
	UI_SOUND_MAP_ZOOM_IN		= 32, 
	UI_SOUND_MAP_ZOOM_OUT		= 33, 
	UI_SOUND_SKILL_ICON_PICK	= 50,	// 스킬 아이템 집기
	UI_SOUND_SKILL_ICON_DROP	= 51,	// 스킬 아이템 놓기
	UI_SOUND_ITEM_PUT_DEFAULT	= 52,
	UI_SOUND_ITEM_PUT_ARMOR		= 53,
	UI_SOUND_ITEM_PUT_ACSSORY	= 54,
	UI_SOUND_ITEM_PUT_BOTTLE	= 55,
	UI_SOUND_ITEM_PUT_WEAPON	= 56,
	UI_SOUND_ITEM_PUT_MONEY		= 57,
    UI_SOUND_ITEM_PUT_CRYSTALIZATION = 58,
	UI_SOUND_STYLE_CHANGE       = 82,

	UI_SOUND_COMPOSE_ENCHANT_SUCCESS = 513,
	UI_SOUND_COMPOSE_ENCHANT_FAIL	 = 511,
	UI_SOUND_COMPOSE_RANKUP_SUCCESS  = 514,
	UI_SOUND_COMPOSE_RANKUP_FAIL	 = 511,
	UI_SOUND_COMPOSE_CRYSTALIZE_TRY	 = 512,
	UI_SOUND_COMPOSE_ACCESSORY_CREATE= 515,
	UI_SOUND_COMPOSE_ACCESSORY_FAIL  = 511,

	UI_SOUND_QUEST_ACCEPT			 = 501,
	UI_SOUND_QUEST_PROGRESS			 = 503,
	UI_SOUND_QUEST_COMPLETE			 = 502,
	UI_SOUND_QUEST_CANCEL			 = 504,
	UI_SOUND_QUEST_INPERFECT_COMPLATE= 505,

	UI_SOUND_HELP_POPUP				 = 522,
	UI_SOUND_HELP_CLICK				 = 521,

	UI_SOUND_ITEM_CLICK_VALIDATION			= 560,
	UI_SOUND_ITEM_VALIDATION_START			= 561,
	UI_SOUND_ITEM_VALIDATION_NUMBER_ROLLING	= 562,
	UI_SOUND_ITEM_VALIDATION_NUMBER_SET		= 563,
	UI_SOUND_ITEM_VALIDATION_COMPLEATE		= 564,

	UI_SOUND_PET_FULLNESS			= 565,
	UI_SOUND_PET_INTIMACY			= 566,

    UI_SOUND_MISSION_OBJECT = 573,

    UI_SOUND_CUBE_OPEN = 578,
    UI_SOUND_CUBE_CLOSE = 577,
    UI_SOUND_CUBE_COMPOSITION_SUCCESS = 574,
    UI_SOUND_CUBE_DECOMPOSITION = 575,
    UI_SOUND_CUBE_COMPOSITION_FAIL = 581,
    UI_SOUND_ZARD_SUCCESS = 583,
    UI_SOUND_ZARD_FAIL = 584,
    UI_SOUND_ZARD_SUCCESS_SECTION = 582,
    UI_SOUND_ZARD_FAIL_SECTION_01 = 593,
    UI_SOUND_ZARD_FAIL_SECTION_02 = 594,
    UI_SOUND_ZARD_FAIL_SECTION_03 = 595,
    UI_SOUND_ZARD_FAIL_SECTION_04 = 596,

    UI_SOUND_SKILLTREE_BUTTON = 585,
    UI_SOUND_SKILLTREE_KEYOPEN = 587,
    UI_SOUND_SKILLTREE_KEYDOWN = 589,
    UI_SOUND_SKILLTREE_KEYCLOSE = 591,
    UI_SOUND_SKILLTREE_BLUEEFFECT = 588,
    UI_SOUND_SKILLTREE_BLINKBLOCK = 590,
    UI_SOUND_SKILLTREE_GAUGEDOWN_01 = 586,
    UI_SOUND_SKILLTREE_GAUGEDOWN_02 = 592,
    UI_SOUND_SKILLTREE_GAUGEDOWN_03 = 597,
    UI_SOUND_SKILLTREE_GAUGEDOWN_04 = 598,
    UI_SOUND_SKILLTREE_GAUGEDOWN_05 = 599,

    UI_SOUND_DICE_ROLL = 602,
    UI_SOUND_DICE_STOP = 603,
    UI_SOUND_DICE_STOP_WIN = 576, // 큐브드랍 소리 사용함
    UI_SOUND_DICE_DROPITEM = 604,
};

