#pragma once

#include <PacketStruct_AD.h>
#include "PacketHandler.h"

// <PROTOTYPEs>
class DBProxyServerSession;

//-------------------------------------------------------------------------------------------------

#define HANDLER_AD_DECL( fnName )		\
	static VOID On##fnName( DBProxyServerSession* pServerSession, MSG_BASE* pMsg, WORD wSize )

#define HANDLER_AD_IMPL( fnName )		\
	VOID Handler_AD::On##fnName( DBProxyServerSession* pServerSession, MSG_BASE* pMsg, WORD wSize )



class Handler_AD
{
public:
	static VOID		RegisterHandler_ALL( PACKET_HANDLER_DELEGATOR pInstance );
private:
	static sPACKET_HANDLER_INFO*	GetHandlerInfo();

public:
	//------------------------------------------------------------------------------
	// <PACKET HANDLERs>
	// Declaration & Implementation
	//
    HANDLER_AD_DECL(AD_CONNECTION_GROUND_CMD);
    HANDLER_AD_DECL(AD_CONNECTION_DBCONNECT_UPDATE_CMD);

	HANDLER_AD_DECL( AD_CHARINFO_CHARLISTREQ_ACK );
	HANDLER_AD_DECL( AD_CHARINFO_CHARLISTREQ_NAK );
	HANDLER_AD_DECL( AD_CHARINFO_CREATE_ACK );
	HANDLER_AD_DECL( AD_CHARINFO_CREATE_NAK );
	HANDLER_AD_DECL( AD_CHARINFO_DESTROY_ACK );
	HANDLER_AD_DECL( AD_CHARINFO_DESTROY_NAK );

	HANDLER_AD_DECL( AD_CHARINFO_RECOVER_ACK );
	HANDLER_AD_DECL( AD_CHARINFO_RECOVER_NAK );

#ifdef __NA_001044_ADD_CUSTOM_UI
	HANDLER_AD_DECL( AD_CHARINFO_CHECK_CHARACTERID_ACK );
	HANDLER_AD_DECL( AD_CHARINFO_CHECK_CHARACTERID_NAK );
#endif
#ifdef __NA000000_SHOP_USERID_50_PASSING_PROC__
    HANDLER_AD_DECL( SERVERCOMMON_QUERY_CHARINFO_ACK );
#endif
    //_KR_0_20091021_FIRENDINVITATION_EXTEND = {
    HANDLER_AD_DECL( AD_EVENT_INVITATIONR_INSERT_CMD );    
    HANDLER_AD_DECL( AD_EVENT_INVITATEFRIEND_REWARD_LIST_NAK );    
    HANDLER_AD_DECL( AD_EVENT_INVITATEFRIEND_REWARD_LIST_ACK );    
    //}
#ifdef _JP_20110222_INGAME_CHARNAME_CHANGE
    HANDLER_AD_DECL( AD_CHARNAME_CHANGE_ACK );
    HANDLER_AD_DECL( AD_CHARNAME_CHANGE_NAK );
#endif

#ifdef _NA_0_20110329_GAMEOPTION_SETTING
    HANDLER_AD_DECL( AD_ETC_GAMEOPTION_SELECT_ACK );
    HANDLER_AD_DECL( AD_ETC_GAMEOPTION_SELECT_NAK );
    HANDLER_AD_DECL(AD_ETC_GAMEOPTION_UPDATE_ACK);
#endif //_NA_0_20110329_GAMEOPTION_SETTING
#ifdef _NA004034_20120102_GUILD_POINT_SYSTEM
    HANDLER_AD_DECL(AD_ETC_GUILD_RANKINGINFO_ACK);
    HANDLER_AD_DECL(AD_ETC_GUILDINFO_ACK);
#endif //_NA004034_20120102_GUILD_POINT_SYSTEM
};

