//	RandomGeneratorPrototypes.h
#pragma once

#include <Protocol.h>

#define USIGNED64_T		(__int64)
#define BU64DECLARE		const __int64

//#define _RNDFN_S( val, bit )	\
//	( ((val)<<(bit)) | ( ((val)&0xFFFFFFFF) >> (32-(bit)) ) )
//
////#define _RNDFN_R( val, tmp )	\
////	{							\
////		tmp = 
//
//#define _RNDFN_F(x, y, z)		\
//	( (z) ^ ((x) & ((y) ^ (z))) )
//
//#define _RNDFN_K	0x5A827999
//
//#define _RNDFN_P( a, b, c, d, e, x )								\
//	{																\
//		e += _RNDFN_S( a, 1 ) + _RNDFN_F( b, c, d ) + _RNDFN_K + x;	\
//		b = _RNDFN_S( b, 30 );										\
//	}





//////////////////////////////////////////////////////////////////////////

#define CRYPT_ODD_NUMBER_INITIAL		(CATEGORY_ODD_NUMBER)
#define CRYPT_ODD_NUMBER_SERVICE		(PROTOCOL_ODD_NUMBER)


BU64DECLARE ODD_CRYPT_INITIAL_RANDOM_NUMBER =	USIGNED64_T(( (__int64)-CRYPT_ODD_NUMBER_INITIAL - ((C2S_HIGH_VERSION_NO)*100) - ((C2S_MIDDLE_VERSION_NO)*100)) );	// ÀÏ´Ü °íÁ¤ ³­¼ö°ª (È¦¼ö ¹øÈ£)
BU64DECLARE ODD_CRYPT_SERVICE_RANDOM_NUMBER =	USIGNED64_T(( (__int64)-CRYPT_ODD_NUMBER_SERVICE - ((C2S_HIGH_VERSION_NO)*100) - ((C2S_MIDDLE_VERSION_NO)*10)) );
//#define ODD_CRYPT_INITIAL_RANDOM_NUMBER	( CRYPT_ODD_NUMBER_INITIAL + (((C2S_HIGH_VERSION_NO+7)<<4) + ((C2S_MIDDLE_VERSION_NO+3)<<5)) )	// ÀÏ´Ü °íÁ¤ ³­¼ö°ª (È¦¼ö ¹øÈ£)
//#define ODD_CRYPT_SERVICE_RANDOM_NUMBER	( CRYPT_ODD_NUMBER_SERVICE - (((C2S_HIGH_VERSION_NO+3)<<7) + ((C2S_MIDDLE_VERSION_NO+7)<<9)) )

#define CRYPT_KEY_INITIAL_GENERATOR(num)	( (BYTE)( ((ODD_CRYPT_INITIAL_RANDOM_NUMBER)*(num))%(TYPE_MAX_ROUND()) ) )
#define CRYPT_KEY_SERVICE_GENERATOR(num)	( (BYTE)( ((ODD_CRYPT_SERVICE_RANDOM_NUMBER)*(num))%(TYPE_MAX_ROUND()) ) )

BU64DECLARE INDEX_CRYPT_RANDOM_NUMBER =		USIGNED64_T( -((__int64)ODD_CRYPT_INITIAL_RANDOM_NUMBER)*(ODD_CRYPT_SERVICE_RANDOM_NUMBER) );
//#define INDEX_CRYPT_RANDOM_NUMBER			( ((__int64)ODD_CRYPT_INITIAL_RANDOM_NUMBER)*(ODD_CRYPT_SERVICE_RANDOM_NUMBER) )
#define INDEX_CRYPT_GENERATOR(num)			( (BYTE)( ((INDEX_CRYPT_RANDOM_NUMBER)*(num))%(TYPE_MAX_ROUND()) ) )

//////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////
// HEX (16) °³ ·£´ý

#define TYPE_MAX_HEXA_ROUND()			(16)
#define CRYPT_ODD_NUMBER_HEX1			((CATEGORY_ODD_NUMBER)%3000)
#define CRYPT_ODD_NUMBER_HEX2			((PROTOCOL_ODD_NUMBER)%3000)

//BU64DECLARE  ODD_CRYPT_HEX1_RANDOM_NUMBER	=	USIGNED64_T( CRYPT_ODD_NUMBER_HEX1 + (((C2S_HIGH_VERSION_NO)*100) + ((C2S_MIDDLE_VERSION_NO)*10)) );
//BU64DECLARE  ODD_CRYPT_HEX2_RANDOM_NUMBER	=	USIGNED64_T( CRYPT_ODD_NUMBER_HEX2 - (((C2S_HIGH_VERSION_NO)*10) + ((C2S_MIDDLE_VERSION_NO)*100)) );
BU64DECLARE  ODD_CRYPT_HEX1_RANDOM_NUMBER	=	USIGNED64_T( -CRYPT_ODD_NUMBER_HEX1 - (C2S_HIGH_VERSION_NO)*100 - ((C2S_MIDDLE_VERSION_NO)*100) );
BU64DECLARE  ODD_CRYPT_HEX2_RANDOM_NUMBER	=	USIGNED64_T( -CRYPT_ODD_NUMBER_HEX2 - (C2S_HIGH_VERSION_NO)*10 - ((C2S_MIDDLE_VERSION_NO)*100) );

#define CRYPT_KEY_HEX1_GENERATOR(num)		( (BYTE)0xF&( ((ODD_CRYPT_HEX1_RANDOM_NUMBER)*(num))%(TYPE_MAX_HEXA_ROUND()) ) )
#define CRYPT_KEY_HEX2_GENERATOR(num)		( (BYTE)0xF&( ((ODD_CRYPT_HEX2_RANDOM_NUMBER)*(num))%(TYPE_MAX_HEXA_ROUND()) ) )

BU64DECLARE INDEX_HEX_RANDOM_NUMBER			=	USIGNED64_T( -(CRYPT_ODD_NUMBER_HEX1)*(CRYPT_ODD_NUMBER_HEX2) );
#define INDEX_HEX_GENERATOR(num)			( (BYTE)( ((INDEX_HEX_RANDOM_NUMBER)*(num))%(TYPE_MAX_HEXA_ROUND()) ) )

//////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////
// OCTET (8) °³ ·£´ý

#define TYPE_MAX_OCT_ROUND()			(8)
#define CRYPT_ODD_NUMBER_OCT1			((CATEGORY_ODD_NUMBER)%3000)
#define CRYPT_ODD_NUMBER_OCT2			((PROTOCOL_ODD_NUMBER)%3000)

BU64DECLARE  ODD_CRYPT_OCT1_RANDOM_NUMBER	=	USIGNED64_T( -CRYPT_ODD_NUMBER_OCT1 - (C2S_HIGH_VERSION_NO)*100 - ((C2S_MIDDLE_VERSION_NO)*100) );
BU64DECLARE  ODD_CRYPT_OCT2_RANDOM_NUMBER	=	USIGNED64_T( -CRYPT_ODD_NUMBER_OCT2 - (C2S_HIGH_VERSION_NO)*100 - ((C2S_MIDDLE_VERSION_NO)*10) );
#define CRYPT_KEY_OCT1_GENERATOR(num)		( (BYTE)0x7&( ((ODD_CRYPT_OCT1_RANDOM_NUMBER)*(num))%(TYPE_MAX_OCT_ROUND()) ) )
#define CRYPT_KEY_OCT2_GENERATOR(num)		( (BYTE)0x7&( ((ODD_CRYPT_OCT2_RANDOM_NUMBER)*(num))%(TYPE_MAX_OCT_ROUND()) ) )

BU64DECLARE INDEX_OCT_RANDOM_NUMBER			=	USIGNED64_T( -(ODD_CRYPT_OCT1_RANDOM_NUMBER)*(ODD_CRYPT_OCT2_RANDOM_NUMBER) );
#define INDEX_OCT_GENERATOR(num)			( (BYTE)( ((INDEX_OCT_RANDOM_NUMBER)*(num))%(TYPE_MAX_OCT_ROUND()) ) )

//////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////
// DWORD (4) °³ ·£´ý

#define TYPE_MAX_DWORD_ROUND()			(4)
#define CRYPT_ODD_NUMBER_DWORD1			((CATEGORY_ODD_NUMBER)%3000)
#define CRYPT_ODD_NUMBER_DWORD2			((PROTOCOL_ODD_NUMBER)%3000)

BU64DECLARE  ODD_CRYPT_DWORD1_RANDOM_NUMBER =	USIGNED64_T( -CRYPT_ODD_NUMBER_DWORD1 - ((C2S_HIGH_VERSION_NO)*10) - ((C2S_MIDDLE_VERSION_NO)*10) );
BU64DECLARE  ODD_CRYPT_DWORD2_RANDOM_NUMBER	=	USIGNED64_T( -CRYPT_ODD_NUMBER_DWORD2 - ((C2S_HIGH_VERSION_NO)*100) - ((C2S_MIDDLE_VERSION_NO)*100) );
#define CRYPT_KEY_DWORD1_GENERATOR(num)	( (BYTE)0x3&( ((ODD_CRYPT_DWORD1_RANDOM_NUMBER)*(num))%(TYPE_MAX_DWORD_ROUND()) ) )
#define CRYPT_KEY_DWORD2_GENERATOR(num)	( (BYTE)0x3&( ((ODD_CRYPT_DWORD2_RANDOM_NUMBER)*(num))%(TYPE_MAX_DWORD_ROUND()) ) )

BU64DECLARE INDEX_DWORD_RANDOM_NUMBER		=	USIGNED64_T( -(ODD_CRYPT_DWORD1_RANDOM_NUMBER)*(ODD_CRYPT_DWORD2_RANDOM_NUMBER) );
#define INDEX_DWORD_GENERATOR(num)		( (BYTE)( ((INDEX_DWORD_RANDOM_NUMBER)*(num))%(TYPE_MAX_DWORD_ROUND()) ) )


//////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////
// WORD (2) °³ ·£´ý

#define TYPE_MAX_WORD_ROUND()			(2)
#define CRYPT_ODD_NUMBER_WORD1			((CATEGORY_ODD_NUMBER)%3000)
#define CRYPT_ODD_NUMBER_WORD2			((PROTOCOL_ODD_NUMBER)%3000)

BU64DECLARE  ODD_CRYPT_WORD1_RANDOM_NUMBER	=	USIGNED64_T( -CRYPT_ODD_NUMBER_WORD1 - ((C2S_HIGH_VERSION_NO)*10) - ((C2S_MIDDLE_VERSION_NO)*100) );
BU64DECLARE  ODD_CRYPT_WORD2_RANDOM_NUMBER	=	USIGNED64_T( -CRYPT_ODD_NUMBER_WORD2 - ((C2S_HIGH_VERSION_NO)*100) - ((C2S_MIDDLE_VERSION_NO)*10) );
#define CRYPT_KEY_WORD1_GENERATOR(num)	( (BYTE)0x1&( ((ODD_CRYPT_WORD1_RANDOM_NUMBER)*(num))%(TYPE_MAX_WORD_ROUND()) ) )
#define CRYPT_KEY_WORD2_GENERATOR(num)	( (BYTE)0x1&( ((ODD_CRYPT_WORD2_RANDOM_NUMBER)*(num))%(TYPE_MAX_WORD_ROUND()) ) )

BU64DECLARE INDEX_WORD_RANDOM_NUMBER		=	USIGNED64_T( -(ODD_CRYPT_WORD1_RANDOM_NUMBER)*(ODD_CRYPT_WORD2_RANDOM_NUMBER) );
#define INDEX_WORD_GENERATOR(num)		( (BYTE)( ((INDEX_WORD_RANDOM_NUMBER)*(num))%(TYPE_MAX_WORD_ROUND()) ) )


#include "RandomGeneratorDeclares.h"

//////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////
// 4 °¡Áö ¼±ÅÃ¹® (0,1,2,3)
#if		C2S_MIDDLE_VERSION_NO == 0
#	define CODE_SELECTOR_BY_VER		0
#elif	C2S_MIDDLE_VERSION_NO == 1
#	define CODE_SELECTOR_BY_VER		3
#elif	C2S_MIDDLE_VERSION_NO == 2
#	define CODE_SELECTOR_BY_VER		2
#elif	C2S_MIDDLE_VERSION_NO == 3
#	define CODE_SELECTOR_BY_VER		1
#elif	C2S_MIDDLE_VERSION_NO == 4
#	define CODE_SELECTOR_BY_VER		0
#elif	C2S_MIDDLE_VERSION_NO == 5
#	define CODE_SELECTOR_BY_VER		3
#elif	C2S_MIDDLE_VERSION_NO == 6
#	define CODE_SELECTOR_BY_VER		1
#elif	C2S_MIDDLE_VERSION_NO == 7
#	define CODE_SELECTOR_BY_VER		2
#elif	C2S_MIDDLE_VERSION_NO == 8
#	define CODE_SELECTOR_BY_VER		3
#elif	C2S_MIDDLE_VERSION_NO == 9
#	define CODE_SELECTOR_BY_VER		0
#endif


//¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦¬¦´
//
//
const DWORD ROUND_CHK_1st_NO = (HEX_KEY_1_GENERATOR_002+OCT_KEY_1_GENERATOR_001);
const DWORD ROUND_CHK_2nd_NO = (HEX_KEY_1_GENERATOR_007+OCT_KEY_1_GENERATOR_002);
const DWORD ROUND_CHK_3rd_NO = (HEX_KEY_1_GENERATOR_011+OCT_KEY_1_GENERATOR_003);
const DWORD ROUND_CHK_4th_NO = (HEX_KEY_1_GENERATOR_014+OCT_KEY_1_GENERATOR_004);
const DWORD ROUND_CHK_5th_NO = (HEX_KEY_1_GENERATOR_001+OCT_KEY_1_GENERATOR_005);
const DWORD ROUND_CHK_6th_NO = (HEX_KEY_1_GENERATOR_009+OCT_KEY_1_GENERATOR_006);
const DWORD ROUND_CHK_7th_NO = (HEX_KEY_1_GENERATOR_005+OCT_KEY_1_GENERATOR_007);
const DWORD ROUND_CHK_8th_NO = (HEX_KEY_1_GENERATOR_008+OCT_KEY_1_GENERATOR_008);

// {1,3,5,7,9,11,13,15},17,19,21
// { 0001 0011 0101 0111 1001 1011 1101 1111 } 1|0001 1|0011 1|0101

#define BUILTIN_CODE_RND_MARK(val)	(val)
#define BUILTIN_CODE_RND_MARK01		BUILTIN_CODE_RND_MARK(0x0001)
#define BUILTIN_CODE_RND_MARK03		BUILTIN_CODE_RND_MARK(0x0011)
#define BUILTIN_CODE_RND_MARK05		BUILTIN_CODE_RND_MARK(0x0101)
#define BUILTIN_CODE_RND_MARK07		BUILTIN_CODE_RND_MARK(0x0111)
#define BUILTIN_CODE_RND_MARK09		BUILTIN_CODE_RND_MARK(0x1001)
#define BUILTIN_CODE_RND_MARK11		BUILTIN_CODE_RND_MARK(0x1011)
#define BUILTIN_CODE_RND_MARK13		BUILTIN_CODE_RND_MARK(0x1101)
#define BUILTIN_CODE_RND_MARK15		BUILTIN_CODE_RND_MARK(0x1111)

#define BUILTIN_CODE_COND_TRUE(cmp)		((CATEGORY_ODD_NUMBER&(cmp)) == (cmp))

#if		BUILTIN_CODE_COND_TRUE(BUILTIN_CODE_RND_MARK01)
#endif
#if		BUILTIN_CODE_COND_TRUE(BUILTIN_CODE_RND_MARK03)
#endif
#if		BUILTIN_CODE_COND_TRUE(BUILTIN_CODE_RND_MARK05)
#endif
#if		BUILTIN_CODE_COND_TRUE(BUILTIN_CODE_RND_MARK07)
#endif
#if		BUILTIN_CODE_COND_TRUE(BUILTIN_CODE_RND_MARK09)
#endif
#if		BUILTIN_CODE_COND_TRUE(BUILTIN_CODE_RND_MARK11)
#endif
#if		BUILTIN_CODE_COND_TRUE(BUILTIN_CODE_RND_MARK13)
#endif
#if		BUILTIN_CODE_COND_TRUE(BUILTIN_CODE_RND_MARK15)
#endif

#if		BUILTIN_CODE_COND_TRUE(BUILTIN_CODE_RND_MARK01)
#elif	BUILTIN_CODE_COND_TRUE(BUILTIN_CODE_RND_MARK03)
#elif	BUILTIN_CODE_COND_TRUE(BUILTIN_CODE_RND_MARK05)
#elif	BUILTIN_CODE_COND_TRUE(BUILTIN_CODE_RND_MARK07)
#elif	BUILTIN_CODE_COND_TRUE(BUILTIN_CODE_RND_MARK09)
#elif	BUILTIN_CODE_COND_TRUE(BUILTIN_CODE_RND_MARK11)
#elif	BUILTIN_CODE_COND_TRUE(BUILTIN_CODE_RND_MARK13)
#elif	BUILTIN_CODE_COND_TRUE(BUILTIN_CODE_RND_MARK15)
#endif



