#pragma once
#ifndef RANKING_LIB_DEFINE_H
#define RANKING_LIB_DEFINE_H

enum eRANKING_SERIALIZE
{
    RANKING_SERIALIZE_LOAD,
    RANKING_SERIALIZE_SAVE,
    RANKING_SERIALIZE_CLIENT_LOAD,
    RANKING_SERIALIZE_CLIENT_SAVE,
};


enum eRANKING_SYSTEM_TYPE
{
    eRANKING_TYPE_NONE          = 0,
    eRANKING_TYPE_TIME_ATTACK   = 1,
    eRANKING_TYPE_POINT         = 2,
#ifdef _NA_006801_20130705_RENEWAL_RANKINGSYSTEM
    // eRANKING_TYPE_BATTLEGROUND_WIN 이후의 값은 전장랭킹 관련된 값만 넣기로 한다.
    // (BattleGroundRankingManager에서 패킷루프를 위한 약속)
    eRANKING_TYPE_BATTLEGROUND_WIN = 3,
    eRANKING_TYPE_BATTLEGROUND_KILL = 4,
    eRANKING_TYPE_BATTLEGROUND_ASSIST = 5,
    eRANKING_TYPE_MAX,
#endif //_NA_006801_20130705_RENEWAL_RANKINGSYSTEM
};

#endif //RANKING_LIB_DEFINE_H