#pragma once
#ifndef GAMESERVER_CG_ITEM_H
#define GAMESERVER_CG_ITEM_H

#include "./PacketHandler.h"




#define Handler_CG_ITEM_DECL(p) \
    static void On##p(ServerSession* pServerSession, MSG_BASE* pMsg, WORD wSize)
#define Handler_CG_ITEM_IMPL(p) \
    void Handler_CG_ITEM::On##p(ServerSession* pServerSession, MSG_BASE* pMsg, WORD wSize)


class Handler_CG_ITEM
{
public:
    Handler_CG_ITEM();
    ~Handler_CG_ITEM();

    // changes, f100819.1L
    static const nsPacket::PacketHandlerInfo GetPacketHandlerNodes();

    Handler_CG_ITEM_DECL(CG_ITEM_MOVE_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_PICK_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_DROP_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_COMBINE_SYN);

    Handler_CG_ITEM_DECL(CG_ITEM_USE_SYN);


    Handler_CG_ITEM_DECL(CG_ITEM_SELL_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_BUY_SYN);

    Handler_CG_ITEM_DECL(CG_ITEM_PICK_MONEY_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_DROP_MONEY_SYN);

    Handler_CG_ITEM_DECL(CG_ITEM_EXCHANGE_SYN);

    Handler_CG_ITEM_DECL(CG_ITEM_ENCHANTUP_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_SOCKET_FILL_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_SOCKET_EXTRACT_SYN);
    //Handler_CG_ITEM_DECL(CG_ITEM_ACCESSORY_CREATE_SYN);

    Handler_CG_ITEM_DECL(CG_ITEM_QUICK_LINKITEM_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_QUICK_LINKSKILL_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_QUICK_UNLINK_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_QUICK_MOVE_SYN);
#if SUN_CODE_BACKUP
    // NOTE: f110216.2L, unused section
    Handler_CG_ITEM_DECL(CG_ITEM_QUICK_UPDATE_LINKED_ITEM_CMD);
#endif
    Handler_CG_ITEM_DECL(CG_ITEM_ENCHANT_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_DIVIDE_SYN);

    Handler_CG_ITEM_DECL(CG_ITEM_COMPOSE_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_CRYSTALIZE_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_EXTRASTONE_USE_SYN);

    Handler_CG_ITEM_DECL(CG_ITEM_DELETE_SYN);

    Handler_CG_ITEM_DECL(CG_ITEM_REPAIR_DURA_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_PORTAL_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_CLEAR_COORD_SYN);

    Handler_CG_ITEM_DECL(CG_ITEM_INIT_STAT_SYN);                                //초기화 아이템 사용  

    Handler_CG_ITEM_DECL(CG_ITEM_INVENTORY_PWD_SETTING_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_INVENTORY_PWD_CHECK_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_INVENTORY_PWD_LOCKING_SYN);

#ifdef __NA_001027_20080423_RANDOM_REWARD_EVENT_
    Handler_CG_ITEM_DECL(CG_ITEM_EXCHANGE_REWARD_ITEM_SYN);
#endif

    Handler_CG_ITEM_DECL(CG_ITEM_HAMMER_OF_ALCHEMIST_SYN);

    Handler_CG_ITEM_DECL(CG_ITEM_VALIDATION_OF_REIHALT_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_USE_PET_ITEM_SYN);

    Handler_CG_ITEM_DECL(CG_ITEM_USE_PANDORA_ITEM_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_MOVE_PANDORA_ITEM_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_MOVE_ALL_PANDORA_ITEM_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_PANDORABOX_CLOSE_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_REPURCHASE_SYN);

    Handler_CG_ITEM_DECL(CG_ITEM_EQUIP_ETHER_DEVICE_SYN);

    Handler_CG_ITEM_DECL(CG_ITEM_STAT_CHANGE_USE_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_STAT_CHANGE_SELECT_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_USE_MOTION_SYN);

    Handler_CG_ITEM_DECL(CG_ITEM_USE_CHANGE_PET_NAME_ITEM_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_ACTIVE_ETHER_BULLET_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_IDENTIFY_POSSESSION_SYN);
    //__NA_0_CASH_ITEM_RENEWAL_SUPERMASTER
    Handler_CG_ITEM_DECL(CG_ITEM_FIXED_AMOUNT_EX_ITEM_FIRE_UP_SYN);
    //__NA001390_090915_RIDING_SYSTEM__
    Handler_CG_ITEM_DECL(CG_ITEM_RIDER_CONTROL_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_RIDER_CONTROL_PARTS_SYN);
    //_NA_0_20091030_RANDOM_ITEM
    Handler_CG_ITEM_DECL(CG_ITEM_USE_RANDOM_ITEM_SYN);

#ifdef _NA_1419_20100121_ACCUMULATE_POINT
    Handler_CG_ITEM_DECL(CG_ITEM_QUERY_ACCUMULATE_POINT_ITEM_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_USE_ACCUMULATE_POINT_SYN);
#endif
    //_NA000023_090323_ENHANCED_INVENTORY_SLOT_FUNCTIONALITY_
    Handler_CG_ITEM_DECL(CG_ITEM_INVENTORY_CONFIG_CHANGE_SYN);
    //_NA000109_100427_ITEM_CUSTOMIZING_CONTENTS_
    Handler_CG_ITEM_DECL(CG_ITEM_ETHERIA_CONTROL_SYN);
    //_NA_000096_20100527_CHANGE_CHARACTER_APPEARANCE_SYSTEM
    Handler_CG_ITEM_DECL(CG_ITEM_CHANGE_CHARACTER_APPEARANCE_SYN); // 캐릭터 외모 변경 아이템 사용 요청을 처리한다.
    Handler_CG_ITEM_DECL(CG_ITEM_COMPOSE_OR_DECOMPOSE_SYN); // 아이템 합성 또는 분해 요청을 처리한다.
    Handler_CG_ITEM_DECL(CG_ITEM_GET_COMPOSITION_OR_DECOMPOSITION_HISTORIES_SYN); // 성공한 합성 또는 분해 내역 요청을 처리한다.
    Handler_CG_ITEM_DECL(CG_ITEM_MODIFY_COMPOSITION_OR_DECOMPOSITION_HISTORIES_CMD); // 합성 또는 분해 내역 수정 요청을 처리한다.
#ifdef _NA_000251_20100727_SOCKET_SYSTEM
    Handler_CG_ITEM_DECL(CG_ITEM_IDENTIFY_SOCKET_CMD); // 아이템 소켓 확인 요청을 처리한다.
    Handler_CG_ITEM_DECL(CG_ITEM_RECREATE_SOCKET_SYN); // 소켓 다시 생성 요청을 처리한다.
#endif // _NA_000251_20100727_SOCKET_SYSTEM

#ifdef _NA_0_20110613_GAME_SHOP_RENEWAL
    Handler_CG_ITEM_DECL(CG_ITEM_USE_EXTEND_DATE_SYN);
#endif
    // _NA_003740_20111122_RANDOM_ITEM
    Handler_CG_ITEM_DECL(CG_ITEM_RANDOMIZE_SYN); // 아이템 랜덤화 요청을 처리한다.

#ifdef _NA_008124_20150313_AWAKENING_SYSTEM
    Handler_CG_ITEM_DECL(CG_ITEM_AWAKENING_SYN);
    Handler_CG_ITEM_DECL(CG_ITEM_EVOLUTION_SYN);
#endif // _NA_008124_20150313_AWAKENING_SYSTEM
#ifdef _NA_008069_20150210_ADD_SPA_SYSTEM
    Handler_CG_ITEM_DECL(CG_ITEM_SPA_COSTUME_CHANGE_SYN);
#endif //_NA_008069_20150210_ADD_SPA_SYSTEM
};

#endif //GAMESERVER_CG_ITEM_H