#pragma once
#ifndef __HANDLER_DG_CHARINFO_H__
#define __HANDLER_DG_CHARINFO_H__

#include "./PacketHandler.h"

#define Handler_DG_CHARINFO_DECL(p) \
    static void On##p(ServerSession* pServerSession, MSG_BASE* pMsg, WORD wSize)
#define Handler_DG_CHARINFO_IMPL(p) \
    void Handler_DG_CHARINFO::On##p(ServerSession* pServerSession, MSG_BASE* pMsg, WORD wSize)



class Handler_DG_CHARINFO
{
public:
    Handler_DG_CHARINFO() {}
    ~Handler_DG_CHARINFO() {}

    // changes, f100819.1L
    static const nsPacket::PacketHandlerInfo GetPacketHandlerNodes();

    //Handler_DG_CHARINFO_DECL(DG_ITEM_WAREHOUSEITEMALL_ACK);
    Handler_DG_CHARINFO_DECL(DG_ITEM_SERIAL_ACK);
    Handler_DG_CHARINFO_DECL(DG_ITEM_SERIAL_NAK);
    Handler_DG_CHARINFO_DECL(DG_CHARINFO_CHAR_ITEM_CMD);
#ifdef _NA_20100106_REPURCHAS_BUGFIX_2496
    Handler_DG_CHARINFO_DECL(DG_CHARINFO_CHAR_REPURCHASE_ITEM_CMD);
#endif //_NA_20100106_REPURCHAS_BUGFIX_2496
    //_KR_0_20091021_FIRENDINVITATION_EXTEND
    Handler_DG_CHARINFO_DECL(DG_CHARINFO_INVITATEDFRIEND_CMD);
#ifdef C_NA_0_20100520_ACSYSTEM_CHANGED	
	Handler_DG_CHARINFO_DECL(DG_CHARINFO_CHAR_ACHIEVEMENT_CMD);
#endif

#ifdef _NA_0_20110308_SKILL_COOL_TIME_STORAGE
    Handler_DG_CHARINFO_DECL(DG_CHARINFO_SKILL_COOL_TIME_CMD);
#endif

    Handler_DG_CHARINFO_DECL(DG_CHARINFO_SKILL_CMD);
    Handler_DG_CHARINFO_DECL(DG_CHARINFO_QUICK_CMD);
    Handler_DG_CHARINFO_DECL(DG_CHARINFO_STYLE_CMD);
    Handler_DG_CHARINFO_DECL(DG_CHARINFO_QUEST_CMD);
    Handler_DG_CHARINFO_DECL(DG_CHARINFO_EXTRA_CMD);
    //Handler_DG_CHARINFO_DECL(DG_CHARINFO_UDPATE_ACK);
    //Handler_DG_CHARINFO_DECL(DG_CHARINFO_UDPATE_NAK);
    //Handler_DG_CHARINFO_DECL(DG_CHARINFO_ALL_REQ_ACK);
    //Handler_DG_CHARINFO_DECL(DG_CHARINFO_ALL_REQ_NAK);
    // declared by _NA002217_100728_EP2_PERK_SYSTEM_
    Handler_DG_CHARINFO_DECL(DG_CHARINFO_SKILL_LIST_CMD);
    Handler_DG_CHARINFO_DECL(DG_CHARINFO_SKILL_PERK_CMD);
    Handler_DG_CHARINFO_DECL(DG_CHARINFO_SKILL_PERK_CONTROL_CMD);

    Handler_DG_CHARINFO_DECL(DG_CHARINFO_QUERY_ACK);
    Handler_DG_CHARINFO_DECL(DG_CHARINFO_QUERY_NAK);
    Handler_DG_CHARINFO_DECL(DG_CHARINFO_UPDATE_ACK);
    Handler_DG_CHARINFO_DECL(DG_CHARINFO_UPDATE_NAK);
    Handler_DG_CHARINFO_DECL(DG_ITEM_INVENTORY_FLAG_STREAM_CMD);

    Handler_DG_CHARINFO_DECL(DG_WAREHOUSE_START_ACK);
    Handler_DG_CHARINFO_DECL(DG_WAREHOUSE_START_NAK);

    Handler_DG_CHARINFO_DECL(DG_WAREHOUSE_END_ACK);
    Handler_DG_CHARINFO_DECL(DG_WAREHOUSE_END_NAK);

    Handler_DG_CHARINFO_DECL(DG_WAREHOUSE_FLAG_STREAM_CMD);
    Handler_DG_CHARINFO_DECL(DG_WAREHOUSE_PWD_SETTING_ACK);

    Handler_DG_CHARINFO_DECL(DG_EVENT_SELECT_ACK);
    Handler_DG_CHARINFO_DECL(DG_EVENT_SELECT_NAK);

    Handler_DG_CHARINFO_DECL(DG_EVENT_UPDATE_ACK);
    Handler_DG_CHARINFO_DECL(DG_EVENT_UPDATE_NAK);

    // 오픈베타 에테르 이벤트
    Handler_DG_CHARINFO_DECL(DG_EVENT_ITEM_STATUS_ACK);
    Handler_DG_CHARINFO_DECL(DG_EVENT_ITEM_STATUS_NAK);

    Handler_DG_CHARINFO_DECL(DG_EVENT_ITEM_REG_ACK);
    Handler_DG_CHARINFO_DECL(DG_EVENT_ITEM_REG_NAK);

    Handler_DG_CHARINFO_DECL(DG_EVENT_USETIME_CMD);

    Handler_DG_CHARINFO_DECL(DG_EVENT_QUERY_EXIST_ACK);

    Handler_DG_CHARINFO_DECL(DG_EVENT_STATUS_UPDATE_ACK);

    Handler_DG_CHARINFO_DECL(DG_EVENT_SSQ_REWARD_EXIST_CMD);
    Handler_DG_CHARINFO_DECL(DG_EVENT_SSQ_REWARD_UPDATE_ACK);

    // 미션 랭킹 관련
    Handler_DG_CHARINFO_DECL(DG_MISSION_RECORD_SELECT_CMD);
    //Handler_DG_CHARINFO_DECL(DG_MISSION_CLEAR_UPDATE_ACK);
    //Handler_DG_CHARINFO_DECL(DG_MISSION_CLEAR_UPDATE_NAK);
    Handler_DG_CHARINFO_DECL(DG_MISSION_RECORD_UPDATE_ACK);
    Handler_DG_CHARINFO_DECL(DG_MISSION_RECORD_UPDATE_NAK);

    Handler_DG_CHARINFO_DECL(DG_OTHER_EXIST_CHARNAME_ACK);
    Handler_DG_CHARINFO_DECL(DG_OTHER_EXIST_CHARNAME_NAK);

    Handler_DG_CHARINFO_DECL(DG_OTHER_SHOP_RECV_GIFT_NTF);

#ifdef __CN_OO0510__FATIGUE_MATCHING_UPDATE
    Handler_DG_CHARINFO_DECL(DG_OTHER_FATIGUE_CMD);
#endif

    Handler_DG_CHARINFO_DECL(DG_WAYPOINT_INFO_LOAD_ACK);
    Handler_DG_CHARINFO_DECL(DG_WAYPOINT_INFO_LOAD_NAK);
    Handler_DG_CHARINFO_DECL(DG_WAYPOINT_INFO_SAVE_ACK);
    Handler_DG_CHARINFO_DECL(DG_WAYPOINT_INFO_SAVE_NAK);
    Handler_DG_CHARINFO_DECL(DG_CHAR_WAYPOINT_INFO_LOAD_ACK);
    Handler_DG_CHARINFO_DECL(DG_CHAR_WAYPOINT_INFO_SAVE_ACK);
    Handler_DG_CHARINFO_DECL(DG_CHAR_WAYPOINT_INFO_DEL_ACK);
    Handler_DG_CHARINFO_DECL(DG_CHAR_WAYPOINT_INFO_NAK);
    //
    Handler_DG_CHARINFO_DECL(DG_MISSION_RANKING_POINT_REQ_ACK);

    Handler_DG_CHARINFO_DECL(DG_GUILD_WAREHOUSE_CLOSE_ACK);
    Handler_DG_CHARINFO_DECL(DG_GUILD_WAREHOUSE_CLOSE_NAK);
    Handler_DG_CHARINFO_DECL(DG_GUILD_WAREHOUSE_TAPEX_ACK);
    Handler_DG_CHARINFO_DECL(DG_GUILD_WAREHOUSE_TAPEX_NAK);
    //{__NA001283_20090227_COLLECTION_LIST
    Handler_DG_CHARINFO_DECL(DG_COLLECT_LIST_LOAD_ACK);
    Handler_DG_CHARINFO_DECL(DG_COLLECT_ADD_ACK);
    Handler_DG_CHARINFO_DECL(DG_COLLECT_DEL_ACK);
    Handler_DG_CHARINFO_DECL(DG_COLLECT_NAK);
    //}
    Handler_DG_CHARINFO_DECL(DG_OTHER_HEIM_LOTTO_PICK_NTF);
#ifdef _NA_1419_20100121_ACCUMULATE_POINT
    Handler_DG_CHARINFO_DECL(DG_OTHER_ACCUMULATEPOINT_MATCHDATE_NTF);
#endif
    Handler_DG_CHARINFO_DECL(DG_OTHER_SELECT_COMPOSITION_OR_DECOMPOSITION_HISTORIES_ACK);
    Handler_DG_CHARINFO_DECL(DG_OTHER_EXTEND_CHAR_SLOT_ACK);
    //_KR_0_20091021_FIRENDINVITATION_EXTEND = {
    Handler_DG_CHARINFO_DECL(DG_EVENT_INVITATEFRIEND_REWARDUPDATE_ACK);
    Handler_DG_CHARINFO_DECL(DG_EVENT_INVITATEFRIEND_REWARDUPDATE_NAK);
    Handler_DG_CHARINFO_DECL(DG_EVENT_INVITATEFRIEND_RECALLSELECT_ACK);
    Handler_DG_CHARINFO_DECL(DG_EVENT_INVITATEFRIEND_RECALLSELECT_NAK);
    //}
#ifdef _NA_20100420_CHANGE_SYSTEM_MEMO_LOGIC
    Handler_DG_CHARINFO_DECL(DG_EVENT_DOMINATION_REWARD_AND_DEL_ACK);
    Handler_DG_CHARINFO_DECL(DG_EVENT_LOTTO_REWARD_AND_DEL_ACK);
#endif
    //_NA_20100812_INTEGRATE_SYSTEM_MEMO_DOMINATION
    Handler_DG_CHARINFO_DECL( DG_EVENT_SYSTEMMEMO_ITEM_CHECK_ACK );
#ifdef _NA_003027_20111013_HONOR_SYSTEM
    Handler_DG_CHARINFO_DECL(DG_CHARINFO_HONORSYSTEM);
#endif //_NA_003027_20111013_HONOR_SYSTEM
#ifdef _NA004034_20120102_POINT_WALLET_SYSTEM
    Handler_DG_CHARINFO_DECL(DG_CHARINFO_POINTWALLET_SYSTEM);
#endif //_NA004034_20120102_POINT_WALLET_SYSTEM
#ifdef _NA004034_20120102_GUILD_POINT_SYSTEM
    Handler_DG_CHARINFO_DECL(DG_CHARINFO_GUILDPOINT_SYSTEM);
#endif //_NA004034_20120102_GUILD_POINT_SYSTEM
    Handler_DG_CHARINFO_DECL(DG_CHARNAME_CHANGE_ACK);
    Handler_DG_CHARINFO_DECL(DG_CHARACTER_EXTRA_INFO_CMD);
#ifdef _NA_000000_20140120_SMART_NPC_SYSTEM
    Handler_DG_CHARINFO_DECL(DG_EVENT_SMARTNPC_SYSTEM);
#endif //_NA_000000_20140120_SMART_NPC_SYSTEM
#ifdef _NA_007086_20140318_MONSTERBOOK
    Handler_DG_CHARINFO_DECL(DG_CHARACTER_MONSTERBOOK_CMD);
#endif //_NA_007086_20140318_MONSTERBOOK

#ifdef _NA_007932_20150106_USER_EXTRA_INFO
    Handler_DG_CHARINFO_DECL(DG_USER_EXTRA_INFO_CMD);
#endif // _NA_007932_20150106_USER_EXTRA_INFO

#ifdef _NA_007919_20141211_ADD_GMCOMMAND_EVENT
    Handler_DG_CHARINFO_DECL(DG_GMEVENT_PEAKTIME_REGISTER_ACK);
    Handler_DG_CHARINFO_DECL(DG_GMEVENT_PEAKTIME_TERMINATE_ACK);
#endif //_NA_007919_20141211_ADD_GMCOMMAND_EVENT

#ifdef _NA_008012_20150204_SUN_RANKING_SYSTEM
    Handler_DG_CHARINFO_DECL(DG_SUN_RANKING_UPDATE_ACK);
    Handler_DG_CHARINFO_DECL(DG_SUN_RANKING_SELECT_ACK);
    Handler_DG_CHARINFO_DECL(DG_SUN_RANKING_INIT_ACK);
    Handler_DG_CHARINFO_DECL(DG_SUN_RANKING_GRADE_INSERT_ACK);
    Handler_DG_CHARINFO_DECL(DG_SUN_RANKING_GRADE_INIT_ACK);
    Handler_DG_CHARINFO_DECL(DG_SUN_RANKING_GRADE_SELECT_ACK);
    Handler_DG_CHARINFO_DECL(DG_STATUE_SELECT_ACK);
    Handler_DG_CHARINFO_DECL(DG_STATUE_ITEM_SLOT_INFO_INSERT_ACK);
    Handler_DG_CHARINFO_DECL(DG_SUN_RANKING_SETTLE_START_CMD);
    Handler_DG_CHARINFO_DECL(DG_SUN_RANKING_SETTLE_COMPLETE_CMD);
    Handler_DG_CHARINFO_DECL(DG_SUN_RANKING_SELECT_COMPLETE_CMD);
    Handler_DG_CHARINFO_DECL(DG_SUN_RANKING_GRADE_SELECT_COMPLETE_CMD);
#endif // _NA_008012_20150204_SUN_RANKING_SYSTEM
};


#endif // __HANDLER_DG_CHARINFO_H__