#pragma once
#ifndef GAMESERVER_CG_GUILD_H
#define GAMESERVER_CG_GUILD_H

#include "./PacketHandler.h"




#define Handler_CG_GUILD_DECL(p) \
    static void On##p(ServerSession* pServerSession, MSG_BASE* pRecvMsg, WORD wSize)
#define Handler_CG_GUILD_IMPL(p) \
    void Handler_CG_GUILD::On##p(ServerSession* pServerSession, MSG_BASE* pRecvMsg, WORD wSize)

class Handler_CG_GUILD
{
public:
    Handler_CG_GUILD(){}
    ~Handler_CG_GUILD(){}

    // changes, f100819.1L
    static const nsPacket::PacketHandlerInfo GetPacketHandlerNodes();

    Handler_CG_GUILD_DECL(CG_GUILD_CREATE_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_DESTROY_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_INVITE_SYN);

    Handler_CG_GUILD_DECL(CG_GUILD_KICKPLAYER_SYN);             // 길드장이 길드원 강제탈퇴 요청
    Handler_CG_GUILD_DECL(CG_GUILD_WITHDRAW_SYN);                   // 길드원이 길드 탈퇴.
    Handler_CG_GUILD_DECL(CG_GUILD_DONATE_UP_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_CONVERT_UP2GP_SYN);

    Handler_CG_GUILD_DECL(CG_GUILD_CHANGE_DUTY_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_RIGHT_DELEGATION_LIST_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_RIGHT_DELEGATION_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_CHANGE_MASTER_SYN);

    Handler_CG_GUILD_DECL(CG_GUILD_CREATE_CORPS_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_DESTROY_CORPS_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_EMPTY_COMMANDER_INFO_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_CHANGE_COMMANDER_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_CHANGE_CORPS_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_CREATE_REAR_CAMP_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_DESTROY_REAR_CAMP_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_INVITE_ANSWER_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_JOIN_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_TOTALINFO_REQ_SYN);

    Handler_CG_GUILD_DECL(CG_GUILD_RELATION_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_RELATION_ANSWER_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_RELATION_BOTH_AGAINST_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_RELATION_DELETE_SYN);

    Handler_CG_GUILD_DECL(CG_GUILD_ADD_INFO_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_RECOVERY_GUILD_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_GUILDMARK_REGISTER_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_GUILDMARK_DELETE_SYN);

    Handler_CG_GUILD_DECL(CG_GUILD_WAREHOUSE_OPEN_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_WAREHOUSE_CLOSE_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_WAREHOUSE_MONEY_SYN);

    Handler_CG_GUILD_DECL(CG_GUILD_NAME_CHANGE_SYN);

#ifdef _NA_003923_20120130_GUILD_RENEWAL
    Handler_CG_GUILD_DECL(CG_GUILD_IN_GAME_GUILD_LOG_LIST_REQ);
#endif

#ifdef _NA_004034_20120102_GUILD_INTRODUCTION
    Handler_CG_GUILD_DECL(CG_GUILD_INTRODUCTION_SAVE_SYN);
#endif //_NA_004034_20120102_GUILD_INTRODUCTION

#ifdef _NA_007330_20140620_GUILD_SYSTEM_EXTENSION
    Handler_CG_GUILD_DECL(CG_GUILD_JOIN_REQUEST_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_JOIN_REQUEST_APPROVE_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_JOIN_REQUEST_REJECT_SYN);

    Handler_CG_GUILD_DECL(CG_GUILD_FACILITY_UPGRADE_SYN);
    Handler_CG_GUILD_DECL(CG_GUILD_FACILITY_ACTIVE_SYN);
#endif //_NA_007330_20140620_GUILD_SYSTEM_EXTENSION
};

#endif //GAMESERVER_CG_GUILD_H