#pragma once
#ifndef GAMESERVER_AG_ZONE_H
#define GAMESERVER_AG_ZONE_H

#include "./PacketHandler.h"

#define Handler_AG_ZONE_DECL(p) \
    static void On##p(ServerSession* pServerSession, MSG_BASE* pMsg, WORD wSize)
#define Handler_AG_ZONE_IMPL(p) \
    void Handler_AG_ZONE::On##p(ServerSession* pServerSession, MSG_BASE* pMsg, WORD wSize)




class Handler_AG_ZONE
{
public:
    Handler_AG_ZONE();
    ~Handler_AG_ZONE();

    // changes, f100819.1L
    static const nsPacket::PacketHandlerInfo GetPacketHandlerNodes();

    Handler_AG_ZONE_DECL(AG_ZONE_LOBBY_CREATE_CMD);
    Handler_AG_ZONE_DECL(AG_ZONE_HUNTING_CREATE_CMD);
    Handler_AG_ZONE_DECL(AG_ZONE_MISSION_CREATE_CMD);
    Handler_AG_ZONE_DECL(AG_ZONE_PVP_CREATE_CMD);
    Handler_AG_ZONE_DECL(AG_ZONE_CHUNTION_CREATE_CMD);
    Handler_AG_ZONE_DECL(AG_ZONE_VILLAGE_CREATE_CMD);
    Handler_AG_ZONE_DECL(AG_ZONE_FIELD_CREATE_CMD);
    Handler_AG_ZONE_DECL(AG_ZONE_DOMINATION_FIELD_CREATE_CMD);
    Handler_AG_ZONE_DECL(AG_ZONE_DOMINATION_FIELD_INFO_SYN);

    Handler_AG_ZONE_DECL(AG_ZONE_ROOM_DESTROY_CMD);

    Handler_AG_ZONE_DECL(AG_ZONE_ROOM_JOIN_CMD);
    Handler_AG_ZONE_DECL(AG_ZONE_ROOM_JOIN_SYN);
    Handler_AG_ZONE_DECL(AG_ZONE_ROOM_LEAVE_CMD);
    Handler_AG_ZONE_DECL(AG_ZONE_ROOM_LEAVE_SYN);

    Handler_AG_ZONE_DECL(AG_ZONE_MASTER_CHANGED_CMD);
    Handler_AG_ZONE_DECL(AG_ZONE_PVP_INFO_CMD);
    Handler_AG_ZONE_DECL(AG_ZONE_PORTAL_FIELD_MOVE_SYN);
    Handler_AG_ZONE_DECL(AG_ZONE_RETURN_VILLAGE_SYN);

    Handler_AG_ZONE_DECL(AG_ZONE_CHANGE_SPECIALTYPE_CMD);

    Handler_AG_ZONE_DECL(AG_ZONE_CAN_CREATE_INSTANCE_DUNGEON_SYN);
    Handler_AG_ZONE_DECL(AG_ZONE_INSTANCE_CREATE_CMD);
    Handler_AG_ZONE_DECL(AG_ZONE_TUTORIAL_SKIP_SYN);
    Handler_AG_ZONE_DECL(AG_ZONE_RETURN_TO_ROOM_INFO_SYN);
    Handler_AG_ZONE_DECL(AG_ZONE_CAN_CREATE_100LEVEL_QUEST_MISSION_SYN);

    Handler_AG_ZONE_DECL(AG_ZONE_SSQ_JOIN_INFO_SYN);
    Handler_AG_ZONE_DECL(AG_ZONE_SSQ_JOIN_SYN);
    Handler_AG_ZONE_DECL(AG_ZONE_SSQ_ROOM_CTRL_CMD);
    //__NA1279_1281_090209_TIMELINE_QUEST_BASED_MISSION__
    Handler_AG_ZONE_DECL(AG_ZONE_QUEST_PORTAL_ENTER_SYN);
    //{__NA001281_BATTLEZONE_ENTER_CONSTRAINTS_CHANGE_IN_LOBBY__
    Handler_AG_ZONE_DECL(AG_ZONE_CAN_CREATE_ROOM_SYN);
    Handler_AG_ZONE_DECL(AG_ZONE_LOBBY_CREATE_SYN);
    Handler_AG_ZONE_DECL(AG_ZONE_LOBBY_JOIN_SYN);
    //}
    // _NA_000038_20100316_VIEW_TO_JOINABLE_ROOM_IN_LOBBY
    // (ADD)(20100318)(hukim)(REQ_0038) AG_ZONE_CHECK_MISSION_ROOM_LIST_SYN
    // 에이전트 서버가 요청한 미션방 입장 가능 여부를 검사하여 응답하는 처리기 추가
    Handler_AG_ZONE_DECL(AG_ZONE_CHECK_MISSION_ROOM_LIST_SYN);
    Handler_AG_ZONE_DECL(AG_ZONE_CHANGE_MONSTER_ABILITY_CMD);

    //_NA_20110630_BATTLE_ZONE_RENEWAL
    Handler_AG_ZONE_DECL(AG_ZONE_CAN_CREATE_ROOM_OF_PARTY_SYN);

#ifdef _NA_008069_20150210_ADD_SPA_SYSTEM
    Handler_AG_ZONE_DECL(AG_ZONE_SPAFIELD_CREATE_CMD);
    Handler_AG_ZONE_DECL(AG_ZONE_SPA_ENTER_SYN);

    Handler_AG_ZONE_DECL(AG_ZONE_SPA_LEAVE_SYN);
#endif //_NA_008069_20150210_ADD_SPA_SYSTEM
};

#endif //GAMESERVER_AG_ZONE_H