#pragma once
#ifndef WORLDSERVER_HANDLER_DW_H
#define WORLDSERVER_HANDLER_DW_H

#include <PacketStruct_DW.h>

#include "./PacketHandler.h"

namespace ns_world {
;
class ServerSessionInWorld;

}; //end of namespace

namespace ns_world { namespace handlers {
;

class Handler_DW
{
public:
    static const ns_world::PacketHandlerInfo GetPacketHandlerNodes();
    //
#undef HANDLER_NODE_INFO
#define HANDLER_NODE_INFO(_category_, _protocol_, phase) \
    static void Handler_DW::On##_protocol_(\
        ns_world::ServerSessionInWorld* const server_session, \
        const MSG_BASE* const msg, const uint16_t msg_size)

    HANDLER_NODE_INFO(DW_CONNECTION, DW_CONNECTION_SERVER_INFO_CMD, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_FRIEND, DW_FRIEND_GETLIST_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_FRIEND, DW_FRIEND_GETLIST_NAK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_FRIEND, DW_FRIEND_ADD_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_FRIEND, DW_FRIEND_ADD_NAK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_FRIEND, DW_FRIEND_DEL_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_FRIEND, DW_FRIEND_DEL_NAK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_FRIEND, DW_FRIEND_BLOCK_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_FRIEND, DW_FRIEND_BLOCK_NAK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_FRIEND, DW_FRIEND_BLOCK_FREE_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_FRIEND, DW_FRIEND_BLOCK_FREE_NAK, PHASE_SERVICE);
    //_NA_0_20100527_ADD_CHAR_RELATION_MEMO
    HANDLER_NODE_INFO(DW_FRIEND, DW_FRIEND_DETAIL_INFO_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_FRIEND, DW_FRIEND_DETAIL_INFO_NAK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_FRIEND, DW_FRIEND_MEMO_UPDATE_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_FRIEND, DW_FRIEND_MEMO_UPDATE_NAK, PHASE_SERVICE);

    //채팅금지/허용
    HANDLER_NODE_INFO(DW_GM, DW_GM_CHATBLOCK_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_GM, DW_GM_CHATBLOCK_NAK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_GM, DW_GM_CHATALLOW_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_GM, DW_GM_CHATALLOW_NAK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_GM, DW_GM_CHATBLOCK_UPDATE_NAK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_GM, DW_GM_CHATBLOCKTIME_ANS, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_GM, DW_GM_CHATBLOCKTIME_NAK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_CHAO, DW_CHAO_ADD_REVENGE_CHAR_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_CHAO, DW_CHAO_ADD_REVENGE_CHAR_NAK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_CHAO, DW_CHAO_REMOVE_REVENGE_CHAR_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_CHAO, DW_CHAO_REMOVE_REVENGE_CHAR_NAK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_CHAO, DW_CHAO_PK_REVENGE_CHAR_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_CHAO, DW_CHAO_PK_REVENGE_CHAR_NAK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_MEMO, DW_MEMO_SEND_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_MEMO, DW_MEMO_SEND_NAK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_MEMO, DW_MEMO_LIST_ANS, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_MEMO, DW_MEMO_LIST_NAK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_MEMO, DW_MEMO_VIEW_ANS, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_MEMO, DW_MEMO_VIEW_NAK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_MEMO, DW_MEMO_DELETE_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_MEMO, DW_MEMO_DELETE_NAK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_STATUS, DW_STATUS_INTERCEPTION_ANS, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_STATUS, DW_STATUS_INTERCEPTION_NAK, PHASE_SERVICE);
    //__NA001254_20090109_RTTG_FUNC_ADD
    HANDLER_NODE_INFO(DW_MEMO, DW_MULTIMEMO_SEND_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_GROUP, DW_GROUP_ADD_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_GROUP, DW_GROUP_ADD_NAK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_GROUP, DW_GROUP_DEL_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_GROUP, DW_GROUP_DEL_NAK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_GROUP, DW_GROUP_LIST_ACK, PHASE_SERVICE);
    //__NA_001359_20090619_HEIM_LOTTO_SYSTEM = {
    HANDLER_NODE_INFO(DW_LOTTO, DW_LOTTO_LOAD_ENTRY_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_LOTTO, DW_LOTTO_LOAD_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_LOTTO, DW_LOTTO_WINNER_LIST_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_LOTTO, DW_LOTTO_SAVE_ENTRY_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_LOTTO, DW_LOTTO_ROLLOVER_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_LOTTO, DW_LOTTO_ADD_TICKET_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_LOTTO, DW_LOTTO_REWARD_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_LOTTO, DW_LOTTO_NOTICE_LIST_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_LOTTO, DW_LOTTO_NOTICE_DEL_ACK, PHASE_SERVICE);
    //}
    HANDLER_NODE_INFO(DW_GUILD, DW_DOMINATION_FINDMONEY_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_GUILD, DW_GUILD_WAREHOUSE_LOGLIST_ANS, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_GUILD, DW_GUILD_WAREHOUSE_LOGLIST_NAK, PHASE_SERVICE);
    HANDLER_NODE_INFO(DW_GUILD, DW_GUILD_SELECT_NOTICE_ACK, PHASE_SERVICE);
    //HANDLER_NODE_INFO(DW_GUILD, DW_GUILD_SELECT_NOTICE_NAK, PHASE_SERVICE);
    //
    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_DESTROY_GUILD_CMD, PHASE_SERVICE);
    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_JOIN_GUILD_CMD, PHASE_SERVICE);
    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_WITHDRAW_GUILD_CMD, PHASE_SERVICE);
    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_NOTICE_CMD, PHASE_SERVICE);
#ifdef __NA_000000_20070528_TAIWAN_GUILD_PVP
    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_CHUNTING_PVP_RESULT_CMD, PHASE_SERVICE);
#endif
    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_CHANGE_DUTY_CMD, PHASE_SERVICE);
    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_CHANGE_MASTER_CMD, PHASE_SERVICE);

    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_CHANGE_COMMANDER_CMD, PHASE_SERVICE);
    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_CHANGE_CORPS_CMD, PHASE_SERVICE);
    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_CREATE_REAR_CAMP_CMD, PHASE_SERVICE);
    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_DESTROY_REAR_CAMP_CMD, PHASE_SERVICE);
    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_CREATE_CMD, PHASE_SERVICE);
    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_RESTORE_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_LOGIN_CHAR_CMD, PHASE_SERVICE);
    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_LOGOUT_CHAR_CMD, PHASE_SERVICE);
    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_KICK_PLAYER_CMD, PHASE_SERVICE);
    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_MEMBER_INFO_REQ_ACK, PHASE_SERVICE);

    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_RECOVERY_GUILD_CMD, PHASE_SERVICE);
    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_DESTROY_WAIT_CMD, PHASE_SERVICE);
    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_GUILDMARK_REGISTER_CMD, PHASE_SERVICE);
    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_GUILDMARK_DELETE_CMD, PHASE_SERVICE);
    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_CHANGE_NOTICE_CMD, PHASE_SERVICE);
    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_CHANGE_NOTICE_NAK, PHASE_SERVICE);

    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_NAME_CHANGE_CMD, PHASE_SERVICE);
    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_DOMINATION_RETURNHIME_CMD, PHASE_SERVICE);
    //_NA_0_20100527_ADD_CHAR_RELATION_MEMO
    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_CHECK_CONDITION_ACCESS_DETAIL_INFO_ACK, PHASE_SERVICE);
    HANDLER_NODE_INFO(WZ_GUILD, WZ_GUILD_CHECK_CONDITION_ACCESS_DETAIL_INFO_NAK, PHASE_SERVICE);
    //
    __DISABLE_COPY(Handler_DW);
};

}}; //end of namespace

//==================================================================================================

#endif //WORLDSERVER_HANDLER_DW_H