#pragma once

#define MAX_QUREY_LENGTH								1024

#define MAX_ACCOUNT_LENGTH								21		// ar
//#define MAX_CHARNAME_LENGTH								51		// ar
#define MAX_CHANNELING_LENGTH							21		// battery channeling
#define MAX_CHARNAME_TW_LENGTH							21		// AR_TW
#define MAX_RETMESSAGE_LENGTH							31		// AR_TW

#define MAX_ACCOUNTID_LENGTH							51		// MU HXKR
#define MAX_CHARACTERID_LENGTH							33		// MU HXKR
#define MAX_TYPENAME_LENGTH								21
#define MAX_PRODUCTNAME_LENGTH							51
#define MAX_MESSAGE_LENGTH								201
#define MAX_VERSION_LENGTH								14
#define MAX_POINTNAME_LENGTH							11
#define MAX_RANK_LENGTH									4
#define MAX_VALUE_LENGTH								255
//#define MAX_ITEMNAME_LENGTH								256

#define PROTOCOL_CLIENT_INQUIRE_CASH					0x0071
#define PROTOCOL_SERVER_INQUIRE_CASH					0x0072
#define PROTOCOL_CLIENT_BUYPRODUCT						0x0073
#define PROTOCOL_SERVER_BUYPRODUCT						0x0074
#define PROTOCOL_CLIENT_GIFTPRODUCT						0x0075
#define PROTOCOL_SERVER_GIFTPRODUCT						0x0076
#define PROTOCOL_CLIENT_STORAGELIST						0x0077
#define PROTOCOL_SERVER_STORAGELIST						0x0078
#define PROTOCOL_CLIENT_GIFTCASH						0x0079
#define PROTOCOL_SERVER_GIFTCASH						0x007A
#define PROTOCOL_CLIENT_PRODUCTBUYGIFTCHECK				0x007B
#define PROTOCOL_SERVER_PRODUCTBUYGIFTCHECK				0x007C
#define PROTOCOL_CLIENT_STORAGEUSE						0x007D
#define PROTOCOL_SERVER_STORAGEUSE						0x007E
#define PROTOCOL_CLIENT_STORAGEUSE_ROLLBACK				0x007F
#define PROTOCOL_SERVER_STORAGEUSE_ROLLBACK				0x0080
#define PROTOCOL_CLIENT_STORAGETHROW					0x0081
#define PROTOCOL_SERVER_STORAGETHROW					0x0082
#define PROTOCOL_CLIENT_PRODUCTEVENTLIST				0x0083
#define PROTOCOL_SERVER_PRODUCTEVENTLIST				0x0084
#define PROTOCOL_SERVER_UPDATECATEGORYLIST				0x0085
#define PROTOCOL_SERVER_UPDATEPRODUCTLIST				0x0086
#define PROTOCOL_CLIENT_PACKAGELEFTCOUNT				0x0089
#define PROTOCOL_SERVER_PACKAGELEFTCOUNT				0x008A
#define PROTOCOL_CLIENT_MILEAGESAVE						0x008B
#define PROTOCOL_SERVER_MILEAGESAVE						0x008C
#define PROTOCOL_CLIENT_MILEAGEDEDUCT					0x008D
#define PROTOCOL_SERVER_MILEAGEDEDUCT					0x008E
#define PROTOCOL_CLIENT_MILEAGELIVESAVEUP				0x008F
#define PROTOCOL_SERVER_MILEAGELIVESAVEUP				0x0090
#define PROTOCOL_CLIENT_ITEMSERIALUPDATE				0x0091
#define PROTOCOL_SERVER_ITEMSERIALUPDATE				0x0092
#define PROTOCOL_CLIENT_PRODUCTINFOSELECT				0x0093
#define PROTOCOL_SERVER_PRODUCTINFOSELECT				0x0094

#define PROTOCOL_CLIENT_INQUIRE_SALESVERSION			0x0095
#define PROTOCOL_SERVER_INQUIRE_SALESVERSION			0x0096
#define PROTOCOL_CLIENT_INQUIRE_BANNERVERSION			0x0087
#define PROTOCOL_SERVER_INQUIRE_BANNERVERSION			0x0088

#define PROTOCOL_CLIENT_UPDATEVERSION					0x0097
#define PROTOCOL_SERVER_UPDATEVERSION					0x0098
#define PROTOCOL_CLIENT_UPDATE_BANNERVERSION			0x0099
#define PROTOCOL_SERVER_UPDATE_BANNERVERSION			0x009A

#define PROTOCOL_CLIENT_INQUIRE_GAMEPOINTVALUE			0x009B
#define PROTOCOL_SERVER_INQUIRE_GAMEPOINTVALUE			0x009C

#define PROTOCOL_CLIENT_STORAGELIST_PAGE				0x009D
#define PROTOCOL_SERVER_STORAGELIST_PAGE				0x009E


// KR : Access IP (클라이언트 IP)
#define PROTOCOL_CLIENT_BUYPRODUCT_ADDIP				0x009F
#define PROTOCOL_CLIENT_GIFTPRODUCT_ADDIP				0x00A0
#define PROTOCOL_CLIENT_GIFTCASH_ADDIP					0x00A1

// AR_TW
#define PROTOCOL_CLIENT_INQUIRE_CASH_AR_TW				0x00A2
#define PROTOCOL_SERVER_INQUIRE_CASH_AR_TW				0x00A3
#define PROTOCOL_CLIENT_BUYPRODUCT_AR_TW				0x00A4
#define PROTOCOL_SERVER_BUYPRODUCT_AR_TW				0x00A5


// KR : 보관함 만료시점(DeleteDate) 표시 추가 : 보관함 리스트 조회, 보관함 페이지 조회
#define PROTOCOL_CLIENT_STORAGELIST_EX					0x00A6
#define PROTOCOL_SERVER_STORAGELIST_EX					0x00A7
#define PROTOCOL_CLIENT_STORAGELIST_PAGE_EX				0x00A8
#define PROTOCOL_SERVER_STORAGELIST_PAGE_EX				0x00A9

// MU_GB, SUN_GB : 상품구매/선물 시 DeductMileageFlag 추가 버전 (_SERVER_ 는 PROTOCOL_SERVER_BUYPRODUCT, PROTOCOL_SERVER_GIFTPRODUCT 사용)
#define PROTOCOL_CLIENT_BUYPRODUCT_GB_EX				0x00AA
#define PROTOCOL_CLIENT_GIFTPRODUCT_GB_EX				0x00AB

// 보관함 사용 - 결과값 CashType 추가 버전
#define PROTOCOL_CLIENT_STORAGEUSE_EX					0x00AC
#define PROTOCOL_SERVER_STORAGEUSE_EX					0x00AD

// 보관함 사용 - 결과값 DeductMileageFlag
#define PROTOCOL_CLIENT_STORAGEUSE_EX_DEDUCTMILEAGEFLAG	0x00AE
#define PROTOCOL_SERVER_STORAGEUSE_EX_DEDUCTMILEAGEFLAG	0x00AF

// MU_GB, SUN_GB : 상품구매/선물 시 DeductMileageFlag & AccessIP 추가 버전 (_SERVER_ 는 PROTOCOL_SERVER_BUYPRODUCT, PROTOCOL_SERVER_GIFTPRODUCT 사용)
#define PROTOCOL_CLIENT_BUYPRODUCT_GB_EX_ADDIP			0x00B0
#define PROTOCOL_CLIENT_GIFTPRODUCT_GB_EX_ADDIP			0x00B1

// AR_GB
#define PROTOCOL_CLIENT_BUYPRODUCT_AR_GB_ADDIP			0x00B2
#define PROTOCOL_CLIENT_GIFTPRODUCT_AR_GB_ADDIP			0x00B3


// GameCode
const long MU_KR  		= 112;	// 뮤 국내
const long MU_GB  		= 645;	// 뮤 글로벌
const long MU_JP  		= 699;	// 뮤 일본
const long MU_VN  		= 704;	// 뮤 베트남
const long MU_TW  		= 831;	// 뮤 대만
const long MU_TH  		= 837;	// 뮤 태국
const long R2_KR  		= 721;	// R2 국내
const long BT_KR  		= 731;	// 배터리 국내
const long BT_CNL 		= 811;	// 배터리 국내 : NHN 채널링(_BATTERY_CHANNELING_)
const long AR_KR  		= 822;	// 아크로드 국내
const long AR_GB  		= 417;	// 아크로드 글로벌,대만
const long SUN_KR 		= 113;	// 썬 국내
const long SUN_JP		= 844;	// 썬 일본
const long SUN_GB		= 503;	// 썬 글로벌
const long BT_TH		= 850;	// 배터리 태국
const long SUN_RU		= 856;	// 썬 러시아
const long SUN_CN		= 862;	// 썬 중국


